### ISSUE TITLE
蔡徐坤这个有点吊！

### ISSUE THREAD

**Issue by zncook** [iPERDance/iPERCore#1]
我正喝咖啡呢，当时就喷出来了！

手部模型还略显僵硬，人物骨骼追踪还不是很细腻，其他都还好了，再优化优化吧！

**Comment by piaozhx** [comment]
@zncook 多谢关注! 手部这个问题其实一直是个我们关注的问题, 大部分视频中人物的手只要一动起来(尤其是跳舞的场景)就会有motion blur, 导致无法分辨, 如果专门做手的动作分析在很多情况反而估计的很差, 平均下来还不如手一直是伸着的效果...

**Comment by plutoyuxie** [comment]
太棒了！看起来效果比Nvidia的vid2vid系列方法好很多啊。
好奇坤坤有没有被收录到数据集里，如果有那么会不会存在律师函风险
