### ISSUE TITLE
No `mmcv-full==1.2.0+torch1.7.0+cu101` for Windows!

### ISSUE THREAD

**Issue by d1ddle** [iPERDance/iPERCore#107]
### **ModuleNotFoundError: No module named 'neural_renderer'**
Running `motion_imitate.py` after installing from source using:
GTX 1650 Super, i7-4790K, Win 10 Pro 20H2
CUDA version 10.1;

I get thrown a `ModuleNotFoundError`. **`neural-renderer`** is nowhere to be found, through pip or source files.
A similar package called `neural_renderer_pytorch` exists, but that doesn't seem to install because of `neural_renderer/cuda/load_textures_cuda.cpp(28): error C3861: 'AT_CHECK': identifier not found`.
Here is a solution to this: [neural_render_pytorch github](https://github.com/daniilidis-group/neural_renderer/pull/86)
Apparently in neural_renderer_pytorch "AT_CHECK" needs to be changed to "TORCH_CHECK" to be compatible with Pytorch newer than 1.4. Using `pip freeze` I've found pytorch (torch) is at version 1.8.1.

Here is the initial `ModuleNotFounderror`:
`File "C:\Users\{USER}\Documents\Motion_Imitate\iPERCore\iPERCore\tools\human_digitalizer\renders\nmr.py", line 9, in` `<module>`
    `import neural_renderer_pytorch as nr`
`ModuleNotFoundError: No module named 'neural_renderer'`

**Any fix for this? Should I edit the `AT_CHECK` in` neural_enderer_pytorch` and use that, or is their a different package called `neural_renderer` I need to install?**

## EDIT: Fixed this, just copied `nueral-renderer` folder from binary release. Found after that the properly edited version can be found here - [https://github.com/iPERDance/neural_renderer](https://github.com/iPERDance/neural_renderer)
But it doesn't build the setup.py wheel properly on Windows and fails.
## EDIT2: No `mmcv-full==1.2.0+torch1.7.0+cu101` for Windows!
Don't use any other version - very broken. Also copying mmcv-full from the binary release just throws an error about how it has no `__version__`.
I've noticed the main branch has been slightly changed since the binary release.

**Comment by StevenLiuWen** [comment]
Hi, @d1ddle , in Windows the torch is 1.6, and the mmcv-full is 1.1.5, because there is no offical mmcv-full is builed with torch 1.7 in windows. See https://github.com/iPERDance/iPERCore/blob/main/setup.py#L95-L108 for more details for Windows.
