### ISSUE TITLE
 neuro_renderer install error

### ISSUE THREAD

**Issue by TongHengcheng** [iPERDance/iPERCore#11]
I use command pip install -e .  install, but  neuro_renderer install error,What caused this？
![image](https://user-images.githubusercontent.com/35362026/101884736-1cf73280-3bd4-11eb-9857-2eab9224f863.png)
My configuration environment is as follows：
![image](https://user-images.githubusercontent.com/35362026/101884860-4748f000-3bd4-11eb-9528-616ae0f058db.png)

**Comment by piaozhx** [comment]
refer to issue #12

**Comment by TongHengcheng** [comment]
thanks
