### ISSUE TITLE
Support for CUDA 11 for Windows 

### ISSUE THREAD

**Issue by mcitew** [iPERDance/iPERCore#125]
I have a RTX 30 (mobile) device, based on my understanding is that it is only supported with CUDA 11.x onwards. 

From what I see by looking into setup.py for Windows it does not support that, only CUDA 10.x is supported. Please confirm.

**Comment by mcitew** [comment]
I think I managed to get it working using a new set of pytorch 1.9 and CUDA 11.x. But my graphic GPU ( 6GB )did not have enough memory to try out other tests. Only able to run the trump single source sample anything else GPU runs out of memory.

**Comment by falcyon** [comment]
Hey @mcitew how did you solve this issue? I'm running a 11.1 pytorch 1.8.1 and I have memory issues too.
