### ISSUE TITLE
Compressing the output file - output file framerate

### ISSUE THREAD

**Issue by uerdenemunkh** [iPERDance/iPERCore#127]
First of all, kudos for the great work.

I have a question regarding the output file video. Does the output video files are compressed? (meaning that frame rate is higher than the input video), if so where do change the frame rate for the output file?

**Comment by StevenLiuWen** [comment]
The fps of the output video follows the input video, https://github.com/iPERDance/iPERCore/blob/1c15b8208a4313c91ce6bf7a97a15fe43cee4a74/iPERCore/tools/utils/multimedia/video.py#L623-L658.
