### ISSUE TITLE
No kernel image available for execution

### ISSUE THREAD

**Issue by Jmavd** [iPERDance/iPERCore#128]
While attempting to run the program, I got the error `Error in forward_face_index_map_1: no kernel image is available for execution on the device`. It seems to be an issue with CUDA, but I have in fact installed CUDA 11.1, a version which should work if I were to build it from source. I have a GTX 1660 TI, and am running Windows 10.

**Comment by StevenLiuWen** [comment]
Try to compile the source instead of using the pre-compiled windows version, since the pre-compiled windows version is incompatible with other Nvidia-Cuda compute architecture.
