### ISSUE TITLE
How to train your model on iPER dataset?

### ISSUE THREAD

**Issue by PangzeCheung** [iPERDance/iPERCore#13]
Hi! How to train your model on iPER dataset? Thank you ~

**Comment by zarathustra9527** [comment]
No train.py?
I don't know how to train a new model with another dance video…

**Comment by StevenLiuWen** [comment]
Hi @PangzeCheung and @zarathustra9527, we have updated the iPERCore with 0.2.0 which contains all the training codes, including the preprocessing on iPER dataset, and training on the iPER dataset. Enjoy it.
