### ISSUE TITLE
Failed to run main demo

### ISSUE THREAD

**Issue by AVTV64** [iPERDance/iPERCore#15]
Hi there, I followed a tutorial for the Windows installation of this AI, everything should be installed correctly but when I run the main demo script it gives me this error
![Immagine](https://user-images.githubusercontent.com/75968494/102047147-0c65d880-3ddd-11eb-9191-cd071559a574.png)

I would like to know how to fix this issue, thank you.

**Comment by ZeerDonker** [comment]
Did you forget to install ffmpeg? 

https://github.com/iPERDance/iPERCore/blob/main/docs/install.md

**Comment by AVTV64** [comment]
> Did you forget to install ffmpeg?
> 
> https://github.com/iPERDance/iPERCore/blob/main/docs/install.md

Ok so what I did was to use custom image and video but with the same names as the original demo and and I think the problem has something to do with naming, but I don't know how to fix it:  if I don't put the _1 after the video name it gives me the WinError2 error as shown in the previous post, but if I put it then it gives me a pre-processing error that I will show here 
![Immagine5](https://user-images.githubusercontent.com/75968494/102093511-8ae46980-3e21-11eb-981c-d747df968f19.png)

**Comment by ZeerDonker** [comment]
Delete stuff from `iPERCore\results`

 Could also change the output directory.

**Comment by AVTV64** [comment]
> Delete stuff from `iPERCore\results`
> 
> Could also change the output directory.

still doesn't work, I even tried changing the output directory but still gives me the pre-processing error

**Comment by StevenLiuWen** [comment]
> > Delete stuff from `iPERCore\results`
> > Could also change the output directory.
> 
> still doesn't work, I even tried changing the output directory but still gives me the pre-processing error

Hi, @AVTV64, Could you illustrate all the command shell used for us? Maybe we can find some clues.

**Comment by AVTV64** [comment]
> > > Delete stuff from `iPERCore\results`
> > > Could also change the output directory.
> > 
> > 
> > still doesn't work, I even tried changing the output directory but still gives me the pre-processing error
> 
> Hi, @AVTV64, Could you illustrate all the command shell that you have used for us? Maybe we can find some clues.

I've used this tutorial to install the AI locally on a Windows 10 machine: https://www.youtube.com/watch?v=LHLfCg8kJsA
In the tutorial the author says to use this command to execute the demo: python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "test" --src_path   "path?=./assets/samples/sources/putin/putin.png,name?=putin" --ref_path   "path?=./assets/samples/references/bruno.mp4,name?=bruno,pose_fc?=300"
Note that the sources are correctly named and placed in the command based on my custom inputs that I will show here: 
![issue1](https://user-images.githubusercontent.com/75968494/102243381-678ded00-3efb-11eb-938d-29cf12e72d1d.png)
![issue2](https://user-images.githubusercontent.com/75968494/102243395-6a88dd80-3efb-11eb-8ad4-1890bb460293.png)
When I try to run the demo it gives me this error: ffmpeg -y -i ./assets/samples/references/bruno.mp4 -ab 160k -ac 2 -ar 44100 -vn ./results\primitives\bruno\processed\audio.mp3 -loglevel quiet
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 113, in <module>
    cfg = setup(args)
  File "d:\cazzate\local\ipercore\ipercore-main\iPERCore\services\options\options_setup.py", line 159, in setup
    cfg.meta_data = load_meta_data(cfg)
  File "d:\cazzate\local\ipercore\ipercore-main\iPERCore\services\options\options_setup.py", line 105, in load_meta_data
    meta_proc = MetaProcess(meta_inp, root_primitives_dir)
  File "d:\cazzate\local\ipercore\ipercore-main\iPERCore\services\options\meta_info.py", line 211, in __init__
    meta_input = self.update_meta_input(meta_input, processed_dir)
  File "d:\cazzate\local\ipercore\ipercore-main\iPERCore\services\options\meta_info.py", line 226, in update_meta_input
    extract_audio_from_video(path, audio_path)
  File "d:\cazzate\local\ipercore\ipercore-main\iPERCore\tools\utils\multimedia\video.py", line 532, in extract_audio_from_video
    subprocess.run(cmd)
  File "D:\Programmi\Anaconda\envs\iperc\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Programmi\Anaconda\envs\iperc\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "D:\Programmi\Anaconda\envs\iperc\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

**Comment by cloudweather** [comment]
adding ffmpeg to the environment variables seems to work for some people, maybe you should give that a try.

**Comment by AVTV64** [comment]
> adding ffmpeg to the environment variables seems to work for some people, maybe you should give that a try.

This solved my issue
