### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by haofanwang** [iPERDance/iPERCore#150]
It's an interesting project, but it seems to be a little difficult to run the demo code because of environment problem. Thus, I put my problems and final solution here for anyone who meet the same issues.

**P1**: The provided [Colab](https://colab.research.google.com/drive/1bwUnj-9NnJA2EMr7eWO4I45UuBtKudg_?usp=sharing) cannot work. 

**A1**: It has 2 problems. First, the download link to checkpoints and samples are invalid, you can find new download addresses from [OneDrive](https://github.com/iPERDance/iPERCore/blob/main/docs/install.md). Second, Colab does not support **os.symlink** or **ln -s** now, this will throw an intermediate error.

**P2**: AttributeError: 'ConfigDict' object has no attribute 'nms'

**A2**: This is caused by the conflict between old config and latest version of mmdet/mmcv/mmedit. You can directly modify _YOUR-PATH-TO-MMDET/mmdet/models/dense_heads/rpn_head.py_, and add `cfg.nms = dict(type='nms', iou_threshold=0.7)`. Possibly, you will get another AttributeError of 'max_per_img', thus, you also need to add `cfg.max_per_img = 100` subsequently.

**P3**: RuntimeError: nms is not compiled with GPU support
**P4**: /mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol

**A3&A4**: Those are all because of mm packages. This repo uses relative old version that may not fit CUDA11. I strongly suggest to install the newest version of them (mmcv == 1.5.3, mmdet == 2.25.0, mmedit == 0.15.0) following official instruction. Especially for mmcv-full, you need install the one that match your local torch&cuda version. If it still cannot detect CUDA, just install it from source instead of pip. After reinstall, you may need also do steps in A2.

**P5**: KeyError: '04_left_leg'

**A5**:  In _./iPERCore/tools/human_digitalizer/deformers/link_utils.py_, change '04_left_leg' to '02_left_leg'.

**Comment by haofanwang** [comment]
BTW, most of links from [README](https://github.com/iPERDance/iPERCore/blob/main/docs/scripts_runner.md#human-appearance-transfer-with-motion-imitation-and-novel-view-synthesis) cannot work, it would be great to replace them.

**Comment by Visciera** [comment]
P2: AttributeError: 'ConfigDict' object has no attribute 'nms'

A2: This is caused by the conflict between old config and latest version of mmdet/mmcv/mmedit. You can directly modify _YOUR-PATH-TO-MMDET/mmdet/models/dense_heads/rpn_head.py_, and add `cfg.nms = dict(type='nms', iou_threshold=0.7)`. Possibly, you will get another AttributeError of 'max_per_img', thus, you also need to add `cfg.max_per_img = 100` subsequently.

In which line i had to add this???

**Comment by haofanwang** [comment]
You can refer to error message where the cfg is used.

**Comment by Visciera** [comment]
Sorry for taking so long to response, did u mean like this or not?
        if proposals.numel() > 0:
            dets, _ = batched_nms(proposals, scores, ids, **cfg.nms = dict(type='nms', iou_threshold=0.7)**)
        else:
            return proposals.new_zeros(0, 5)

        return dets[:**cfg.max_per_img = 100**]

**Comment by Visciera** [comment]
Sorry for taking so long to response, did u mean like this or not?
        if proposals.numel() > 0:
            dets, _ = batched_nms(proposals, scores, ids, cfg.nms = dict(type='nms', iou_threshold=0.7))
        else:
            return proposals.new_zeros(0, 5)

        return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
### return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
###aaa

**Comment by Visciera** [comment]
**asasasasas**

**Comment by Visciera** [comment]
### ssssss

**Comment by Visciera** [comment]
_vvdsvdsvdsvs_

**Comment by Visciera** [comment]
if proposals.numel() > 0:
            dets, _ = batched_nms(proposals, scores, ids, cfg.nms = dict(type='nms', iou_threshold=0.7))
        else:
            return proposals.new_zeros(0, 5)

        return dets[:cfg.max_per_img = 100]

**Comment by Visciera** [comment]
dets, _ = batched_nms(proposals, scores, ids, cfg.nms)

**Comment by Visciera** [comment]
Sorry for taking so long to response, did u mean like this or not?

        if proposals.numel() > 0:
            dets, _ = batched_nms(proposals, scores, ids, cfg.nms = dict(type='nms', iou_threshold=0.7))
        else:
            return proposals.new_zeros(0, 5)

        return dets[:cfg.max_per_img = 100]

**Comment by haofanwang** [comment]
I usually set it before calling it, something like below.

```
cfg.nms =  = dict(type='nms', iou_threshold=0.7)
dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
```

**Comment by Visciera** [comment]
I already add this

        if proposals.numel() > 0:
            cfg.nms = dict(type='nms', iou_threshold=0.7)
            dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
        else:
            return proposals.new_zeros(0, 5)

        return dets[:cfg.max_per_img]

and it says

TypeError: 'module' object is not callable

How do i fix this?

**Comment by Visciera** [comment]
Any answer???

**Comment by haofanwang** [comment]
Please be polite. I just provide my solution, but I'm not responsible for this issue.

Closed.
