### ISSUE TITLE
Run motion_imitate.py error

### ISSUE THREAD

**Issue by xiaosuzhang** [iPERDance/iPERCore#19]
when I run a single image as the source inputs in windows,  it cause the error. What caused this?

(venv) E:\DL_with_coding\pytorch\iPERCore>python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 1 --output_dir "./results" --assets_dir "./assets" --model_id "donald_trump_2" --src_path "path?=/data/dev/projects/iPERCore/assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" --ref_path "path?=/data/dev/projects/iPERCore/assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"
------------ Options -------------
{'MAX_NUM_SOURCE': 8,
 'MultiMedia': {'ffmpeg': {'Linux': {'ffmpeg_exe_path': 'ffmpeg',
                                     'ffprobe_exe_path': 'ffprobe'},
                           'Windows': {'ffmpeg_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe',
                                       'ffprobe_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe'},
                           'pix_fmt': 'yuv420p',
                           'vcodec': 'h264'},
                'image': {'caption': 'this is a fake video, synthesized by '
                                     'impersonator++',
                          'saved_name_format': 'pred_{:0>8}.png'}},
 'NUMBER_FACES': 13776,
 'NUMBER_VERTS': 6890,
 'Preprocess': {'BackgroundInpaintor': {'bg_replace': True,
                                        'cfg_path': './assets/configs/inpaintors/mmedit_inpainting.toml',
                                        'dilate_iter_num': 3,
                                        'dilate_kernel_size': 9,
                                        'name': 'mmedit_inpainting',
                                        'use_sr': True},
                'Cropper': {'ref_crop_factor': 3.0, 'src_crop_factor': 1.3},
                'Deformer': {'cloth_parse_ckpt_path': './assets/checkpoints/mattors/exp-schp-lip.pth'},
                'FrontInfo': {'NUM_CANDIDATE': 25, 'RENDER_SIZE': 256},
                'HumanMattors': {'cfg_path': './assets/configs/mattors/point_render+gca.toml',
                                 'dilate_iter_num': 7,
                                 'erode_iter_num': 2,
                                 'morph_kernel_size': 3,
                                 'name': 'point_render+gca'},
                'MAX_PER_GPU_PROCESS': 1,
                'Pose2dEstimator': {'cfg_path': './assets/configs/pose2d/openpose/body25.toml',
                                    'joint_type': 'OpenPose-Body-25',
                                    'name': 'openpose'},
                'Pose3dEstimator': {'batch_size': 32,
                                    'cfg_path': './assets/configs/pose3d/spin.toml',
                                    'name': 'spin',
                                    'num_workers': 4},
                'Pose3dRefiner': {'cfg_path': './assets/configs/pose3d/smplify.toml',
                                  'name': 'smplify',
                                  'use_lfbgs': True},
                'Tracker': {'tracker_name': 'max_box'},
                'estimate_boxes_first': True,
                'filter_invalid': True,
                'has_detector': True,
                'temporal': True,
                'use_smplify': True},
 'Train': {'D_adam_b1': 0.9,
           'D_adam_b2': 0.999,
           'G_adam_b1': 0.9,
           'G_adam_b2': 0.999,
           'aug_bg': False,
           'display_freq_s': 30,
           'face_factor': 1.0,
           'face_loss_path': './assets/checkpoints/losses/sphere20a_20171020.pth',
           'final_lr': 2e-06,
           'lambda_D_prob': 1.0,
           'lambda_face': 5.0,
           'lambda_mask': 5.0,
           'lambda_mask_smooth': 1.0,
           'lambda_rec': 10.0,
           'lambda_tsf': 10.0,
           'lr_D': 0.0001,
           'lr_G': 0.0001,
           'niters_or_epochs_decay': 0,
           'niters_or_epochs_no_decay': 100,
           'num_iters_validate': 1,
           'opti': 'Adam',
           'print_freq_s': 30,
           'save_latest_freq_s': 300,
           'tb_visual': False,
           'train_G_every_n_iterations': 1,
           'use_face': True,
           'use_vgg': 'VGG19',
           'vgg_loss_path': './assets/checkpoints/losses/vgg19-dcbb9e9d.pth'},
 'assets_dir': './assets',
 'batch_size': 1,
 'bg_ks': 11,
 'cam_strategy': 'smooth',
 'cfg_path': './assets\\configs\\deploy.toml',
 'digital_type': 'cloth_smpl_link',
 'dis_name': 'patch_global',
 'face_path': './assets/checkpoints/pose3d/smpl_faces.npy',
 'facial_path': './assets/checkpoints/pose3d/front_facial.json',
 'fim_enc_path': './assets/checkpoints/pose3d/mapper_fim_enc.txt',
 'front_path': './assets/checkpoints/pose3d/front_body.json',
 'ft_ks': 1,
 'gen_name': 'AttLWB-SPADE',
 'gpu_ids': '0',
 'head_path': './assets/checkpoints/pose3d/head.json',
 'image_size': 512,
 'intervals': 1,
 'ip': '',
 'load_epoch': -1,
 'load_path_D': 'None',
 'load_path_G': './assets/checkpoints/neural_renders/AttLWB-SPADE_id_G_2020-05-18.pth',
 'local_rank': 0,
 'map_name': 'uv_seg',
 'meta_data': {'checkpoints_dir': './results\\models\\donald_trump_2',
               'meta_ref': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001C0A4DE3EB8>],
               'meta_src': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001C0A4DE3CC0>],
               'opt_path': './results\\models\\donald_trump_2\\opts.txt',
               'personalized_ckpt_path': './results\\models\\donald_trump_2\\personalized.pth',
               'root_primitives_dir': './results\\primitives'},
 'model_id': 'donald_trump_2',
 'neural_render_cfg': {'Discriminator': {'bg_cond_nc': 4,
                                         'cond_nc': 6,
                                         'max_nf_mult': 8,
                                         'n_layers': 4,
                                         'name': 'patch_global',
                                         'ndf': 64,
                                         'norm_type': 'instance',
                                         'use_sigmoid': False},
                       'Generator': {'BGNet': {'cond_nc': 4,
                                               'n_res_block': 6,
                                               'norm_type': 'instance',
                                               'num_filters': [64,
                                                               128,
                                                               128,
                                                               256]},
                                     'SIDNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'None',
                                                'num_filters': [64, 128, 256]},
                                     'TSFNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'instance',
                                                'num_filters': [64, 128, 256]},
                                     'name': 'AttLWB-SPADE'}},
 'neural_render_cfg_path': './assets/configs/neural_renders/AttLWB-SPADE.toml',
 'num_source': 1,
 'num_workers': 4,
 'only_vis': False,
 'output_dir': './results',
 'part_path': './assets/checkpoints/pose3d/smpl_part_info.json',
 'port': 0,
 'ref_path': 'path?=/data/dev/projects/iPERCore/assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300',
 'serial_batches': False,
 'share_bg': True,
 'smpl_model': './assets/checkpoints/pose3d/smpl_model.pkl',
 'smpl_model_hand': './assets/checkpoints/pose3d/smpl_model_with_hand_v2.pkl',
 'src_path': 'path?=/data/dev/projects/iPERCore/assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2',
 'tb_visual': False,
 'temporal': False,
 'tex_size': 3,
 'time_step': 1,
 'train_name': 'LWGTrainer',
 'use_cudnn': False,
 'use_inpaintor': False,
 'uv_map_path': './assets/checkpoints/pose3d/mapper_uv.txt',
 'verbose': True}
-------------- End ----------------
        Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
        path: /data/dev/projects/iPERCore/assets/samples/sources/donald_trump_2/00000.PNG
        bg_path:
        name: donald_trump_2
primitives_dir: ./results\primitives\donald_trump_2
processed_dir: ./results\primitives\donald_trump_2\processed
vid_info_path: ./results\primitives\donald_trump_2\processed\vid_info.pkl
-------------------------------------------------------
----------------------MetaProcess----------------------
meta_input:
        path: /data/dev/projects/iPERCore/assets/samples/references/akun_2.mp4
        bg_path:
        name: akun_2
        audio:
        fps: 25
        pose_fc: 300.0
        cam_fc: 100
primitives_dir: ./results\primitives\akun_2
processed_dir: ./results\primitives\akun_2\processed
vid_info_path: ./results\primitives\akun_2\processed\vid_info.pkl
-------------------------------------------------------
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "E:\Anaconda\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 41, in run
    device=device
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
    device=device
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "E:\Anaconda\envs\venv\lib\site-packages\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "E:\Anaconda\envs\venv\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "E:\Anaconda\envs\venv\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "E:\Anaconda\envs\venv\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "E:\Anaconda\envs\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\Anaconda\envs\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\options\process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 1.
        Pre-processing: failed...

**Comment by StevenLiuWen** [comment]
Hi, @xiaosuzhang , What's your CUDA version. It seems that there are some problems in the installation procedure of MMCV.
Maybe you can refer to https://github.com/iPERDance/iPERCore/issues/7.
And you can see https://www.youtube.com/watch?v=LHLfCg8kJsA&t=1s&ab_channel=bycloudump for more details.

**Comment by xiaosuzhang** [comment]
I install MMCV  successful, but it also occur errors. Is the GPU memory not enough??

python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 1 --output_dir "./results" --assets_dir "./assets" --model_id "donald_trump_2" --src_path "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" --ref_path "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"
------------ Options -------------
{'MAX_NUM_SOURCE': 8,
 'MultiMedia': {'ffmpeg': {'Linux': {'ffmpeg_exe_path': 'ffmpeg',
                                     'ffprobe_exe_path': 'ffprobe'},
                           'Windows': {'ffmpeg_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe',
                                       'ffprobe_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe'},
                           'pix_fmt': 'yuv420p',
                           'vcodec': 'h264'},
                'image': {'caption': 'this is a fake video, synthesized by '
                                     'impersonator++',
                          'saved_name_format': 'pred_{:0>8}.png'}},
 'NUMBER_FACES': 13776,
 'NUMBER_VERTS': 6890,
 'Preprocess': {'BackgroundInpaintor': {'bg_replace': True,
                                        'cfg_path': './assets/configs/inpaintors/mmedit_inpainting.toml',
                                        'dilate_iter_num': 3,
                                        'dilate_kernel_size': 9,
                                        'name': 'mmedit_inpainting',
                                        'use_sr': True},
                'Cropper': {'ref_crop_factor': 3.0, 'src_crop_factor': 1.3},
                'Deformer': {'cloth_parse_ckpt_path': './assets/checkpoints/mattors/exp-schp-lip.pth'},
                'FrontInfo': {'NUM_CANDIDATE': 25, 'RENDER_SIZE': 256},
                'HumanMattors': {'cfg_path': './assets/configs/mattors/point_render+gca.toml',
                                 'dilate_iter_num': 7,
                                 'erode_iter_num': 2,
                                 'morph_kernel_size': 3,
                                 'name': 'point_render+gca'},
                'MAX_PER_GPU_PROCESS': 1,
                'Pose2dEstimator': {'cfg_path': './assets/configs/pose2d/openpose/body25.toml',
                                    'joint_type': 'OpenPose-Body-25',
                                    'name': 'openpose'},
                'Pose3dEstimator': {'batch_size': 32,
                                    'cfg_path': './assets/configs/pose3d/spin.toml',
                                    'name': 'spin',
                                    'num_workers': 4},
                'Pose3dRefiner': {'cfg_path': './assets/configs/pose3d/smplify.toml',
                                  'name': 'smplify',
                                  'use_lfbgs': True},
                'Tracker': {'tracker_name': 'max_box'},
                'estimate_boxes_first': True,
                'filter_invalid': True,
                'has_detector': True,
                'temporal': True,
                'use_smplify': True},
 'Train': {'D_adam_b1': 0.9,
           'D_adam_b2': 0.999,
           'G_adam_b1': 0.9,
           'G_adam_b2': 0.999,
           'aug_bg': False,
           'display_freq_s': 30,
           'face_factor': 1.0,
           'face_loss_path': './assets/checkpoints/losses/sphere20a_20171020.pth',
           'final_lr': 2e-06,
           'lambda_D_prob': 1.0,
           'lambda_face': 5.0,
           'lambda_mask': 5.0,
           'lambda_mask_smooth': 1.0,
           'lambda_rec': 10.0,
           'lambda_tsf': 10.0,
           'lr_D': 0.0001,
           'lr_G': 0.0001,
           'niters_or_epochs_decay': 0,
           'niters_or_epochs_no_decay': 100,
           'num_iters_validate': 1,
           'opti': 'Adam',
           'print_freq_s': 30,
           'save_latest_freq_s': 300,
           'tb_visual': False,
           'train_G_every_n_iterations': 1,
           'use_face': True,
           'use_vgg': 'VGG19',
           'vgg_loss_path': './assets/checkpoints/losses/vgg19-dcbb9e9d.pth'},
 'assets_dir': './assets',
 'batch_size': 1,
 'bg_ks': 11,
 'cam_strategy': 'smooth',
 'cfg_path': './assets\\configs\\deploy.toml',
 'digital_type': 'cloth_smpl_link',
 'dis_name': 'patch_global',
 'face_path': './assets/checkpoints/pose3d/smpl_faces.npy',
 'facial_path': './assets/checkpoints/pose3d/front_facial.json',
 'fim_enc_path': './assets/checkpoints/pose3d/mapper_fim_enc.txt',
 'front_path': './assets/checkpoints/pose3d/front_body.json',
 'ft_ks': 1,
 'gen_name': 'AttLWB-SPADE',
 'gpu_ids': '0',
 'head_path': './assets/checkpoints/pose3d/head.json',
 'image_size': 512,
 'intervals': 1,
 'ip': '',
 'load_epoch': -1,
 'load_path_D': 'None',
 'load_path_G': './assets/checkpoints/neural_renders/AttLWB-SPADE_id_G_2020-05-18.pth',
 'local_rank': 0,
 'map_name': 'uv_seg',
 'meta_data': {'checkpoints_dir': './results\\models\\donald_trump_2',
               'meta_ref': [<iPERCore.services.options.meta_info.MetaProcess object at 0x00000229D02FE898>],
               'meta_src': [<iPERCore.services.options.meta_info.MetaProcess object at 0x00000229D02FE9B0>],
               'opt_path': './results\\models\\donald_trump_2\\opts.txt',
               'personalized_ckpt_path': './results\\models\\donald_trump_2\\personalized.pth',
               'root_primitives_dir': './results\\primitives'},
 'model_id': 'donald_trump_2',
 'neural_render_cfg': {'Discriminator': {'bg_cond_nc': 4,
                                         'cond_nc': 6,
                                         'max_nf_mult': 8,
                                         'n_layers': 4,
                                         'name': 'patch_global',
                                         'ndf': 64,
                                         'norm_type': 'instance',
                                         'use_sigmoid': False},
                       'Generator': {'BGNet': {'cond_nc': 4,
                                               'n_res_block': 6,
                                               'norm_type': 'instance',
                                               'num_filters': [64,
                                                               128,
                                                               128,
                                                               256]},
                                     'SIDNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'None',
                                                'num_filters': [64, 128, 256]},
                                     'TSFNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'instance',
                                                'num_filters': [64, 128, 256]},
                                     'name': 'AttLWB-SPADE'}},
 'neural_render_cfg_path': './assets/configs/neural_renders/AttLWB-SPADE.toml',
 'num_source': 1,
 'num_workers': 4,
 'only_vis': False,
 'output_dir': './results',
 'part_path': './assets/checkpoints/pose3d/smpl_part_info.json',
 'port': 0,
 'ref_path': 'path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300',
 'serial_batches': False,
 'share_bg': True,
 'smpl_model': './assets/checkpoints/pose3d/smpl_model.pkl',
 'smpl_model_hand': './assets/checkpoints/pose3d/smpl_model_with_hand_v2.pkl',
 'src_path': 'path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2',
 'tb_visual': False,
 'temporal': False,
 'tex_size': 3,
 'time_step': 1,
 'train_name': 'LWGTrainer',
 'use_cudnn': False,
 'use_inpaintor': False,
 'uv_map_path': './assets/checkpoints/pose3d/mapper_uv.txt',
 'verbose': True}
-------------- End ----------------
        Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
        path: ./assets/samples/sources/donald_trump_2/00000.PNG
        bg_path:
        name: donald_trump_2
primitives_dir: ./results\primitives\donald_trump_2
processed_dir: ./results\primitives\donald_trump_2\processed
vid_info_path: ./results\primitives\donald_trump_2\processed\vid_info.pkl
-------------------------------------------------------
----------------------MetaProcess----------------------
meta_input:
        path: ./assets/samples/references/akun_2.mp4
        bg_path:
        name: akun_2
        audio:
        fps: 25
        pose_fc: 300.0
        cam_fc: 100
primitives_dir: ./results\primitives\akun_2
processed_dir: ./results\primitives\akun_2\processed
vid_info_path: ./results\primitives\akun_2\processed\vid_info.pkl
-------------------------------------------------------
        1.1 Preprocessing, running Preprocessor to detect the human boxes of ./results\primitives\donald_trump_2\processed\orig_images...
100%|██████████████████████████████████████████████████████████████████████████████ 100%|██████████████████████████████████████████████████████████████████████████████ ████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/it]
        1.1 Preprocessing, finish detect the human boxes of ./results\primitives\donald_trump_2\processed\orig_images ...
        1.2 Preprocessing, cropping all images in ./results\primitives\donald_trump_2\processed\orig_images by estimated boxes ...
0it [00:00, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\envs\venv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda\envs\venv\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Anaconda\envs\venv\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda\envs\venv\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Anaconda\envs\venv\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Anaconda\envs\venv\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda\envs\venv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\DL_with_coding\pytorch\iPERCore\demo\motion_imitate.py", line 10, in <module>
    from iPERCore.services.run_imitator import run_imitator
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\run_imitator.py", line 4, in <module>
    from iPERCore.models import ModelsFactory
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\models\__init__.py", line 1, in <module>
    from .base_model import BaseModel, ModelsFactory
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\models\base_model.py", line 2, in <module>
    import torch
  File "E:\Anaconda\envs\venv\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda\envs\venv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
0it [00:00, ?it/s]
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 77, in run
    visual=True,
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\tools\processors\base_preprocessor.py", line 88, in execute
    self._execute_crop_img(processed_info, crop_size, bg_path, num_workers=num_workers)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\tools\processors\base_preprocessor.py", line 200, in _execute_crop_img
    all_boxes_XYXY, all_keypoints)):
  File "E:\Anaconda\envs\venv\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "E:\Anaconda\envs\venv\lib\concurrent\futures\process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "E:\Anaconda\envs\venv\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "E:\Anaconda\envs\venv\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "E:\Anaconda\envs\venv\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 80, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\options\process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\dl_with_coding\pytorch\ipercore\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 1.
        Pre-processing: failed...

**Comment by piaozhx** [comment]
>OSError: [WinError 1455] 页面文件太小，无法完成操作

You are right. `"The paging file is too small for this operation to complete"`  is usually caused by insufficient gpu memory. Maybe you are using gpu with 6GB memory (GTX1060, RTX 2060, etc) to render 512x512 images, which need 9.8GB at least (e.g. RTX2080Ti, Titan Xp, V100, etc).

**Comment by xiaosuzhang** [comment]
You are right. The GPU's memory is 6GB. Thank you!!!

**Comment by anguoKuang** [comment]
hello，I'm looking for the "neural_renderer" installation to report an error: 

ERROR: Command errored out with exit status 1:
     command: 'A:\Anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-q
x53uapn\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-qx53uapn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
 open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\User
s\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-eb472ome'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-qx53uapn\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-qx53uapn\setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch.utils'. 

Have you ever reported such a mistake? Please give advice or comments？ Thank you!!!
