### ISSUE TITLE
When can we expect code?

### ISSUE THREAD

**Issue by Devetec** [iPERDance/iPERCore#2]
I know that you are working as quick as possible, and thank you for working on this amazing thing, but when do you expect you'll be done?

**Comment by StevenLiuWen** [comment]
Hi @Devetec, 
Thanks for watching this project, we try, try our best, to make it at the end of this mouth.

**Comment by Devetec** [comment]
Thank you!

**Comment by StevenLiuWen** [comment]
Hi, @Devetec ，we have released our iPERCore-0.1 codes.
