### ISSUE TITLE
There are something wrong when I replace trump's image to mine in clolab notebook

### ISSUE THREAD

**Issue by AaronNZH** [iPERDance/iPERCore#23]
```
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2\""
src_path = "\"path?=images/nzh_01.PNG,name?=nzh_01\""

```

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: failed...

**Comment by piaozhx** [comment]
1. change the `model_id` to "nzh_01". 
2. try using an absolute path instead of the relative path.

**Comment by AaronNZH** [comment]
It worked when i put the image in `"/content/iPERCore/assets/samples/sources/"`
Thanks for your help～
