### ISSUE TITLE
Does it only work with real photos?

### ISSUE THREAD

**Issue by jaeggerr** [iPERDance/iPERCore#25]
Hello,

Thanks a lot for your amazing work.

I'm trying to use this tool to animate 3D characters, dolls and characters created with Photoshop but without success.
I always have this kind of result.
![vlcsnap-2020-12-21-13h46m11s144](https://user-images.githubusercontent.com/3704804/102779820-2c753900-4395-11eb-9f68-66a5b2bfa053.png)
![vlcsnap-2020-12-21-13h46m52s029](https://user-images.githubusercontent.com/3704804/102779823-2f702980-4395-11eb-8ea7-6ff39576ee00.png)

In /results/primitives/modelName/processed/parse, the masks are however correctly extracted
![alpha](https://user-images.githubusercontent.com/3704804/102779851-38f99180-4395-11eb-865e-90d6a7efa106.jpg)

Am I doing something wrong or is the model only trained for real humans?
I don't have any issues with photos of actual people.

My command looks like this:

```sh
python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id "bjd" --src_path "path?=./assets/samples/sources/bjd/bjd.jpg,name?=bjd" --ref_path "path?=./assets/samples/references/akun.mp4,name?=akun,pose_fc?=300"
```

**Comment by StevenLiuWen** [comment]
It seems that there is no personalization. Have you ever reuse the **model_id “bdj”**?  Maybe you need to delete the bdj in the ./results/models and ./resutls/primitives. Be sure that if the input is different, change the model_id with a different name.

**Comment by jaeggerr** [comment]
Hi, I found the issue.
The issue occurs when the source images are too big. Is there a size limit for the source images?
