### ISSUE TITLE
Released version cannot be downloaded

### ISSUE THREAD

**Issue by xiaohong23** [iPERDance/iPERCore#26]
Thank you for this wonderful project.  The released version cannot be downloaded in my area.  I was wondering if you could put it on baiduyun or other cloud drive all people can download.  Thanks.

**Comment by piaozhx** [comment]
@xiaohong23 We have released a new download link based on 天翼云, you can use this link if the original link becomes invalid.

**Comment by xiaohong23** [comment]
Thank you for the excellent work.  I downloaded from 天翼云.
