### ISSUE TITLE
Improve the detection effect of part of human body

### ISSUE THREAD

**Issue by ForgotLove** [iPERDance/iPERCore#27]
When I used the dance video by Ricardo Milos and the image about Trump  for training, at least half of the frames reminded me that I could not detect person. Is it possible to further improve the body mesh recovery module and add human body feature as input of transformation flow T?
Or is there any way to optimize my output for this dance？

**Comment by StevenLiuWen** [comment]
@ForgotLove, currently, the source images and reference videos must be the full body and the half body inputs will result in bad results.

**Comment by ForgotLove** [comment]
> @ForgotLove, currently, the source images and reference videos must be full-body without effects, and the half-body inputs or videos with effects will result in bad results.

OK,thank you.
