### ISSUE TITLE
What requirements to expect?

### ISSUE THREAD

**Issue by mitya12342** [iPERDance/iPERCore#3]
Are we gonna be able to run this on mid range gaming computers? What vram/ram/gpu requirements to expect? Can we expect google collab support?

**Comment by snehitvaddi** [comment]
Yes!! 
I would be great, if there is a Collab notebook to implement this on custom data.
Hope you have this on your todolist.😊

**Comment by piaozhx** [comment]
It depends on the resolution. for example,  512x512 needs 10g gpu memory, 256x256 needs 4.3g. Colab version is also in our project and will be released with code at the same time.

**Comment by thelordlugo** [comment]
> It depends on the resolution. for example, 512x512 needs 10g gpu memory, 256x256 needs 4.3g. Colab version is also in our project and will be released with code at the same time.

hi not to bother you but do you have an exact release date for the code we can test?
Thanks

**Comment by piaozhx** [comment]
@thelordlugo we are sorry for the late, full code will be released this week.

**Comment by mitya12342** [comment]
> @thelordlugo we are sorry for the late, full code will be released this week.

We sure excited about it but don't rush it, take your time 👍

**Comment by Amazingren** [comment]
> It depends on the resolution. for example, 512x512 needs 10g gpu memory, 256x256 needs 4.3g. Colab version is also in our project and will be released with code at the same time.

Hi Zhixin,
Thanks for your impressive work, I wonder what kind of GPU you used and how long will the proposed method take for training a model(i.e. 512 x 512 example on 1080Ti).

**Comment by StevenLiuWen** [comment]
hi @all, Hi, @Devetec ，we have released our iPERCore-0.1 codes. We also provide with the [Google Colab](https://colab.research.google.com/drive/1bwUnj-9NnJA2EMr7eWO4I45UuBtKudg_?usp=sharing).

**Comment by mitya12342** [comment]
Tried it recently on Colab. Examples and my own videos worked nice there in 512x512! Thank you for your impressive work
