### ISSUE TITLE
How do you generate "mabaoguo_back_full_size" with only "mabaoguo_1" known?

### ISSUE THREAD

**Issue by ZM-J** [iPERDance/iPERCore#34]
I'm kind of curious about it.

**Comment by piaozhx** [comment]
Actually, we use two different images from the original video to inpaint unknown area (no deep learning, just PhotoShop).

**Comment by ZM-J** [comment]
Is this function only available in PhotoShop?
I don't have PhotoShop license, but I still want to get back picture. Is there any approach?

**Comment by piaozhx** [comment]
No, it ("mabaoguo_back_full_size") is manually adjusted. but we also have an inpainting network based on `mmdet` in this project. if you do not have the background, it will recognize the foreground person and "remove" it to generate the background.
