### ISSUE TITLE
iPERCore在python3.7 能运行吗？

### ISSUE THREAD

**Issue by gdcrx** [iPERDance/iPERCore#36]
你好，我运行demo/motion_imitate.py报错，请帮忙看看是什么原因。
打印front_info， {'ft': {'body_num': [], 'face_num': [], 'ids': []}, 'bk': {'body_num': [], 'face_num': [], 'ids': []}}
是不是视频帧没拆出来引起？
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "/usr/bin/anaconda3/envs/iPERCore/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jock/iPERCore/iPERCore/services/preprocess.py", line 41, in run
    device=device
  File "/home/jock/iPERCore/iPERCore/tools/processors/preprocessors.py", line 125, in __init__
    device=device
  File "/home/jock/iPERCore/iPERCore/tools/human_mattors/__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "/home/jock/iPERCore/iPERCore/tools/human_mattors/point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/home/jock/iPERCore/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/jock/iPERCore/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/jock/iPERCore/mmdetection/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/jock/iPERCore/mmdetection/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .mean_ap import average_precision, eval_map, print_map_summary
  File "/home/jock/iPERCore/mmdetection/mmdet/core/evaluation/mean_ap.py", line 6, in <module>
    from terminaltables import AsciiTable
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
zlib.error: Error -2 while decompressing data: inconsistent stream state
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "/home/jock/iPERCore/iPERCore/services/preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "/home/jock/iPERCore/iPERCore/services/preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "/home/jock/iPERCore/iPERCore/services/options/process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "/home/jock/iPERCore/iPERCore/services/options/process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/anaconda3/envs/iPERCore/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jock/iPERCore/iPERCore/services/preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 1.

**Comment by piaozhx** [comment]
你是用自己的数据跑的，还是跑trump那个demo？能提供完整的运行指令和运行环境（操作系统，显卡驱动，CUDA，Pytorch版本等等）吗？编译时有没有报错？

**Comment by gdcrx** [comment]
执行的是trump那个demo,用的ubuntu16.04, 显卡NVIDIA Quadro P4000。
编译没有错误。
我在mmdetection下执行 python tools/train.py ./configs/gfl/gfl_r50_fpn_mstrain_2x_coco.py --work-dir 1_work_dirs_gfl_hat_hair_beard --gpu-ids 0
显示信息如下：
sys.platform: linux
Python: 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) [GCC 7.3.0]
CUDA available: True
GPU 0: Quadro P4000
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PyTorch: 1.6.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm                        _70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -                        DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-                        array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-st                        rict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fd                        iagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PER                        F_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON,                         USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0+cu101
OpenCV: 4.4.0
MMCV: 1.1.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.7.0+482f60f

**Comment by gdcrx** [comment]
我在windows下执行：python demo/motion_imitate.py --gpu_ids 0 --image_size 512  --num_source 2   --output_dir "./results"  --assets_dir "./assets" --model_id   "donald_trump_2" --src_path   "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2"  --ref_path   "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"

会出现处理进度条：
 1.1 Preprocessing, running Preprocessor to detect the human boxes of ./results\primitives\donald_trump_2\processed\orig_images...
  0%|                                                                                                                                         | 0/1 [00:02<?, ?it/s]
不过我的GPU只有2G内存，执行不了。
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.18 GiB already allocated; 12.37 MiB free; 1.20 GiB reserved in total by PyTorch)

在linux下执行只显示 Pre-processing: digital deformation start... ，跟着就是上面的错误信息了。

**Comment by piaozhx** [comment]
ubuntu下,你安装ffmpeg了吗

**Comment by gdcrx** [comment]
ffmpeg安装了，有生成mp3文件：results/primitives/akun_2/processed/audio.mp3
执行下面ffmpeg语句正常：
ffmpeg -y -i ./assets/samples/references/akun_2.mp4 -ab 160k -ac 2 -ar 44100 -vn ./results/primitives/akun_2/processed/audio.mp3

ffmpeg version 4.3.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './assets/samples/references/akun_2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:00:17.41, start: 0.000000, bitrate: 1566 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 1432 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to './results/primitives/akun_2/processed/audio.mp3':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    TSSE            : Lavf58.45.100
    Stream #0:0(und): Audio: mp3 (libmp3lame), 44100 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc58.91.100 libmp3lame
size=     341kB time=00:00:17.39 bitrate= 160.5kbits/s speed=39.5x
video:0kB audio:340kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.192267%

**Comment by gdcrx** [comment]
是不是显卡驱动没对应上？
用nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
查看驱动nvidia-smi
显示 CUDA Version: 11.0
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:02:00.0 Off |                  N/A |
| 46%   33C    P5     5W / 105W |     87MiB /  8116MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by piaozhx** [comment]
应该跟驱动没有关系, 应该还是你那边`mmcv`和`mmdet`没有安装成功,你可能忽略了什么报错信息

**Comment by gdcrx** [comment]
安装提示成功，拿图片跑mmdet 的例子可以正常检测。

/iPERCore/mmdetection# pip install -v -e .
Using pip 20.2.4 from /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/pip (python 3.6)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-7bnttvxn
Created temporary directory: /tmp/pip-req-tracker-hugyeltu
Initialized build tracking at /tmp/pip-req-tracker-hugyeltu
Created build tracker: /tmp/pip-req-tracker-hugyeltu
Entered build tracker: /tmp/pip-req-tracker-hugyeltu
Created temporary directory: /tmp/pip-install-tyhhy3mr
Obtaining file:///home/jock/iPERCore/mmdetection
  Added file:///home/jock/iPERCore/mmdetection to build tracker '/tmp/pip-req-tracker-hugyeltu'
    Running setup.py (path:/home/jock/iPERCore/mmdetection/setup.py) egg_info for package from file:///home/jock/iPERCore/mmdetection
    Created temporary directory: /tmp/pip-pip-egg-info-jv_dl2g_
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info
    writing /tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-jv_dl2g_/mmdet.egg-info/SOURCES.txt'
  Source in /home/jock/iPERCore/mmdetection has version 2.7.0, which satisfies requirement mmdet==2.7.0 from file:///home/jock/iPERCore/mmdetection
  Removed mmdet==2.7.0 from file:///home/jock/iPERCore/mmdetection from build tracker '/tmp/pip-req-tracker-hugyeltu'
Requirement already satisfied: matplotlib in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from mmdet==2.7.0) (3.3.3)
Requirement already satisfied: mmpycocotools in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/mmpycocotools-12.0.3-py3.6-linux-x86_64.egg (from mmdet==2.7.0) (12.0.3)
Requirement already satisfied: numpy in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from mmdet==2.7.0) (1.19.3)
Requirement already satisfied: six in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from mmdet==2.7.0) (1.15.0)
Requirement already satisfied: terminaltables in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/terminaltables-3.1.0-py3.6.egg (from mmdet==2.7.0) (3.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from matplotlib->mmdet==2.7.0) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from matplotlib->mmdet==2.7.0) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from matplotlib->mmdet==2.7.0) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from matplotlib->mmdet==2.7.0) (8.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from matplotlib->mmdet==2.7.0) (1.3.1)
Requirement already satisfied: setuptools>=18.0 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from mmpycocotools->mmdet==2.7.0) (51.1.0.post20201221)
Requirement already satisfied: cython>=0.27.3 in /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages (from mmpycocotools->mmdet==2.7.0) (0.29.21)
Installing collected packages: mmdet
  Attempting uninstall: mmdet
    Found existing installation: mmdet 2.7.0
    Uninstalling mmdet-2.7.0:
      Created temporary directory: /tmp/pip-uninstall-vynacxlm
      Removing file or directory /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/mmdet.egg-link
      Removing pth entries from /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/easy-install.pth:
      Removing entry: /home/jock/iPERCore/mmdetection
      Successfully uninstalled mmdet-2.7.0
  Running setup.py develop for mmdet
    Running command /usr/bin/anaconda3/envs/iPERCore2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jock/iPERCore/mmdetection/setup.py'"'"'; __file__='"'"'/home/jock/iPERCore/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    Creating /usr/bin/anaconda3/envs/iPERCore2/lib/python3.6/site-packages/mmdet.egg-link (link to .)
    Adding mmdet 2.7.0 to easy-install.pth file

    Installed /home/jock/iPERCore/mmdetection
Successfully installed mmdet

**Comment by piaozhx** [comment]
@gdcrx 1. 在ubuntu下你不要下载1.1.5版本的mmcv, 用1.2.0版本的(就是我们写在[full_reqs.txt](https://github.com/iPERDance/iPERCore/blob/main/requirements/full_reqs.txt)里面的相关版本, 1.1.5版本是针对windows环境的), 安装完成之后应该会有一个叫`mmcv-full`的包而不是`mmcv`; 

2. 如果你在编译1.2.0版本时遇到编译错误,可以尝试使用GCC8去编译(我的运行环境就是ubuntu16.04 + cuda10.1.243 + GCC8.4.0)

**Comment by gdcrx** [comment]
明天我再试试，我试着跟了下执行过程，跑到iPERCore\tools\human_mattors\__init__.py的from .point_render_parser import PointRenderGCAMattor这句就跑不下去了，下面这句mattor = PointRenderGCAMattor(*args, **kwargs)没执行。

**Comment by gdcrx** [comment]
找不到原因，所有程序全部重新下载。
下面三个组件git下载没动静，到仓库手动下载最新zip包。
git+https://github.com/open-mmlab/mmdetection.git@8179440ec5f75fe95484854af61ce6f6279f3bbc
git+https://github.com/open-mmlab/mmediting@d4086aaf8a36ae830f1714aad585900d24ad1156
git+https://github.com/iPERDance/neural_renderer.git@e5f54f71a8941acf372514eb92e289872f272653
conda环境删除重新建了，全部重新安装，demo例子可以跑了。
@piaozhx  多谢您的耐心指教。
