### ISSUE TITLE
colab result: Two legs are merged like wearing a dress   :-)

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#38]
I'm experimenting on colab with different photos. This is my recent result:
![Screenshot - 20-12-29 15 26 44](https://user-images.githubusercontent.com/34834507/103258879-26add200-49eb-11eb-8051-0b19e0f65213.png)
You can see in the photos that the legs are spread out. But looks like it can't handle pants when they are too wide.

**Comment by piaozhx** [comment]
It seems that the `cloth_smpl_link` mode of `digital_type` failed in your case (which is used for the skirt case). you can close it by following steps: 

1. open`assets/configs/deploy.toml`
2. change the value of `digital_type` to `smpl` (default value is `cloth_smpl_link`)
3. delete all results and rerun the code

**Comment by bigboss97** [comment]
Wow, problem fixed! Thank you so much.
I downloaded _deploy.toml_, modified it and transfered it back. It would be great if there's an option in the colab.

**Comment by bigboss97** [comment]
For some reason there's a black mark flashing around my left arm (right arm when I turn around) all the time:
![Screenshot - 20-12-29 22 36 33](https://user-images.githubusercontent.com/34834507/103281238-71990b00-4a26-11eb-97a6-cb55b95ea2c0.png)
I've tried the same reference video with other source images, with tight sleeves. The result was very clean.

**Comment by piaozhx** [comment]
The sleeves in your image are too wide compared to the body shape of the estimated SMPL model, so the deep network cannot be trained very well in the step of `personalization`, which causes the problem of "black mark".

**Comment by bigboss97** [comment]
I fixed the problem by modifying the sleeves smaller, thanks.
Another question, sometimes I get more "cloudy" edge than other even I was using the same input images:
![Screenshot - 20-12-31 14 00 50](https://user-images.githubusercontent.com/34834507/103392425-f5134300-4b71-11eb-90ab-a52b651dd128.png)
Is there an parameter I can adjust?
