### ISSUE TITLE
No Cuda Runtime Is Found

### ISSUE THREAD

**Issue by WuyWuy** [iPERDance/iPERCore#39]
This Error Happened When I Was Using https://github.com/iPERDance/iPERCore/wiki/How-to-use-the-released-version-on-windows%3F
C:\Users\NGUYEN>E:

E:\motion_imitate>.\motion_imitate.exe --gpu_ids 0 --image_size 256  --num_source 2 `
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
usage: motion_imitate.exe [-h] [--gpu_ids GPU_IDS] [--image_size IMAGE_SIZE] [--num_source NUM_SOURCE]
                          [--output_dir OUTPUT_DIR] [--assets_dir ASSETS_DIR] [--model_id MODEL_ID]
                          [--src_path SRC_PATH] [--ref_path REF_PATH]
motion_imitate.exe: error: unrecognized arguments: `

E:\motion_imitate>--output_dir "./results" --assets_dir "./assets" `
'--output_dir' is not recognized as an internal or external command,
operable program or batch file.

E:\motion_imitate>--model_id   "donald_trump_2" `
'--model_id' is not recognized as an internal or external command,
operable program or batch file.

E:\motion_imitate>--src_path "path?=./assets/samples/sources/wuy/Snapshot_18.png,name?=wuy" `
'--src_path' is not recognized as an internal or external command,
operable program or batch file.

E:\motion_imitate>--ref_path "path?=./assets/samples/references/19.mp4,name?=19,pose_fc?=300"

**Comment by piaozhx** [comment]
Currently, it has some compatibility issues and can only be used on GeForce 10 series GPU. We are trying to fix this problem.

**Comment by piaozhx** [comment]
We will update this issue in #29
