### ISSUE TITLE
error when running "python demo/motion_imitate.py --gpu_ids 2"

### ISSUE THREAD

**Issue by thelordlugo** [iPERDance/iPERCore#4]
see attached screenshot below, any help would be appreciated, Thanks!

<img width="1045" alt="Screen Shot 2020-12-06 at 6 24 52 PM" src="https://user-images.githubusercontent.com/20141834/101296280-7f28ef80-37f0-11eb-842c-53431141a5cb.png">

**Comment by piaozhx** [comment]
it is usually caused by different cuda version between local cuda(`cat /usr/local/cuda/version.txt`) and  pytorch (`pip show torch`).
