### ISSUE TITLE
请问下neural_render安装环境必须要gcc>=7.5.0吗？

### ISSUE THREAD

**Issue by ToTheBeginning** [iPERDance/iPERCore#41]
我在一台gcc7.5.0机器上可以成功安装并且跑起来，但是在另一台机器上，由于某种原因只有gcc7.3.1，在安装neural_render的时候就会报错“error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1”.

请问下除了升级gcc，还有其他解决途径吗？

**Comment by piaozhx** [comment]
没有测试过不同GCC版本的影响, 保险起见还是用GCC7.5以上的版本吧
