### ISSUE TITLE
 no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by lujiayou123** [iPERDance/iPERCore#47]
Error in forward_face_index_map_1: no kernel image is available for execution on the device
Error in forward_face_index_map_2: no kernel image is available for execution on the device
Win10系统
2070super
Driver Version: 460.89
CUDA Version: 11.2
如何解决

**Comment by YuhwaChoong** [comment]
应该是预编译的torch依赖的cuda版本不一致造成的，我用源码在win10上用本地配置好的torch可以直接跑。

**Comment by piaozhx** [comment]
Are you using the pre-compiled version on Windows? Currently, it has some compatibility issues and can only be used on GeForce 10 series GPU. We are trying to fix this problem.

**Comment by piaozhx** [comment]
We will update this issue in #29
