### ISSUE TITLE
Can it use to transfer half person pose?

### ISSUE THREAD

**Issue by AmberCheng** [iPERDance/iPERCore#51]
Hi, thanks for your wonderful work. I wonder does it work for half body pose transfer ?

**Comment by StevenLiuWen** [comment]
Hi @AmberCheng, currently, half body inputs will produce bad results.

**Comment by AmberCheng** [comment]
> Hi @AmberCheng, currently, half body inputs will produce bad results.

@StevenLiuWen I have ever tried half body in impersonator project(you provide before). I wonder does it because the HMR
 will give a squat pose for half body?

**Comment by StevenLiuWen** [comment]
> > Hi @AmberCheng, currently, half body inputs will produce bad results.
> 
> @StevenLiuWen I have ever tried half body in impersonator project(you provide before). I wonder does it because the HMR
> will give a squat pose for half body?

Yes, you are right. Our project relies on a Mesh Recovery Module (HMR or SPIN), and both of them failed on the half body inputs.

**Comment by AmberCheng** [comment]
> > > Hi @AmberCheng, currently, half body inputs will produce bad results.
> > 
> > 
> > @StevenLiuWen I have ever tried half body in impersonator project(you provide before). I wonder does it because the HMR
> > will give a squat pose for half body?
> 
> Yes, you are right. Our project relies on a Mesh Recovery Module (HMR or SPIN), and both of them failed on the half body inputs.

I wonder does it possible to replace Mesh Recovery Module with other method, such as VIBE?

**Comment by StevenLiuWen** [comment]
> > > > Hi @AmberCheng, currently, half body inputs will produce bad results.
> > > 
> > > 
> > > @StevenLiuWen I have ever tried half body in impersonator project(you provide before). I wonder does it because the HMR
> > > will give a squat pose for half body?
> > 
> > 
> > Yes, you are right. Our project relies on a Mesh Recovery Module (HMR or SPIN), and both of them failed on the half body inputs.
> 
> I wonder does it possible to replace Mesh Recovery Module with other method, such as VIBE?

Maybe it is possible, we have not tested the half body inputs on the VIBE or other methods yet. If you find it works for the half body inputs, please notify us (thanks first), and we will update the pose 3d estimator with that kind of method.

**Comment by AmberCheng** [comment]
> > > > > Hi @AmberCheng, currently, half body inputs will produce bad results.
> > > > 
> > > > 
> > > > @StevenLiuWen I have ever tried half body in impersonator project(you provide before). I wonder does it because the HMR
> > > > will give a squat pose for half body?
> > > 
> > > 
> > > Yes, you are right. Our project relies on a Mesh Recovery Module (HMR or SPIN), and both of them failed on the half body inputs.
> > 
> > 
> > I wonder does it possible to replace Mesh Recovery Module with other method, such as VIBE?
> 
> Maybe it is possible, we have not tested the half body inputs on the VIBE or other methods yet. If you find it works for the half body inputs, please notify us (thanks first), and we will update the pose 3d estimator with that kind of method.

Ok, thanks again for your kind reply~~
