### ISSUE TITLE
No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Datadelete10426** [iPERDance/iPERCore#54]
1.6 Preprocessing, finish run background inpainting ....
1.7 Preprocessing, saving visualization to ./results\primitives\donald_trump_2\processed\visual.mp4 ...
Error in forward_face_index_map_1: no kernel image is available for execution on the device
Error in forward_face_index_map_2: no kernel image is available for execution on the device
Error in forward_texture_sampling: no kernel image is available for execution on the device
Error in forward_face_index_map_1: no kernel image is available for execution on the device
Error in forward_face_index_map_2: no kernel image is available for execution on the device
iPERCore\tools\utils\visualizers\smpl_visualizer.py:57: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (Triggered internally at  ..\aten\src\ATen\native\TensorIterator.cpp:924.)

Windows10+python3.8
CUDA从10.1到11.2都尝试过，同样报错

**Comment by piaozhx** [comment]
Are you using the pre-compiled version on Windows? Currently, it has some compatibility issues and can only be used on GeForce 10 series GPU. We are trying to fix this problem.

**Comment by Datadelete10426** [comment]
> Are you using the pre-compiled version on Windows? Currently, it has some compatibility issues and can only be used on GeForce 10 series GPU. We are trying to fix this problem.

Yes, but other versions also have other problems

**Comment by piaozhx** [comment]
We will update this issue in #29
