### ISSUE TITLE
Is there a way to generate the video without reference and source images?

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#55]
Is there any parameter to switch off and generate the synthesis video only?

**Comment by piaozhx** [comment]
Currently, there is only the fused video (source + reference + synthesis). if you only want the synthesis video, you can make it 
with single-frame images by using `FFmpeg`

**Comment by bigboss97** [comment]
Good idea, I'll use the PNG images in my editing software directly.
