### ISSUE TITLE
大佬们运行motion_imitate.py时老是报错mmcv-full 1.1.5版本不匹配怎么解决啊

### ISSUE THREAD

**Issue by bumie7758258** [iPERDance/iPERCore#62]
**运行motion_imitate.py时老是报错mmcv-full 1.1.5版本不匹配怎么解决啊。
以下是我的运行命令和日志**
(venv) C:\WINDOWS\system32>python D:\iPERCore-main\demo\motion_imitate.py  --gpu_ids 0  --image_size 256  --num_source 2    --output_dir "D:\iPERCore-main/results"  --assets_dir "D:\iPERCore-main/assets"   --src_path   "path?=D:\iPERCore-main\assets\samples\sources\donald_trump_2\00000.PNG,name?=donald_trump_2"  --ref_path   "path?=D:\iPERCore-main\assets\samples\references\akun_1.mp4,name?=akun_2,pose_fc?=300"
./assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe -v error -select_streams v -of default=noprint_wrappers=1:nokey=1 -show_entries stream=r_frame_rate D:\iPERCore-main\assets\samples\references\akun_1.mp4
------------ Options -------------
{'MAX_NUM_SOURCE': 8,
 'MultiMedia': {'ffmpeg': {'Linux': {'ffmpeg_exe_path': 'ffmpeg',
                                     'ffprobe_exe_path': 'ffprobe'},
                           'Windows': {'ffmpeg_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe',
                                       'ffprobe_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe'},
                           'pix_fmt': 'yuv420p',
                           'vcodec': 'h264'},
                'image': {'caption': 'this is a fake video, synthesized by '
                                     'impersonator++',
                          'saved_name_format': 'pred_{:0>8}.png'}},
 'NUMBER_FACES': 13776,
 'NUMBER_VERTS': 6890,
 'Preprocess': {'BackgroundInpaintor': {'bg_replace': True,
                                        'cfg_path': './assets/configs/inpaintors/mmedit_inpainting.toml',
                                        'dilate_iter_num': 3,
                                        'dilate_kernel_size': 9,
                                        'name': 'mmedit_inpainting',
                                        'use_sr': True},
                'Cropper': {'ref_crop_factor': 3.0, 'src_crop_factor': 1.3},
                'Deformer': {'cloth_parse_ckpt_path': './assets/checkpoints/mattors/exp-schp-lip.pth'},
                'FrontInfo': {'NUM_CANDIDATE': 25, 'RENDER_SIZE': 256},
                'HumanMattors': {'cfg_path': './assets/configs/mattors/point_render+gca.toml',
                                 'dilate_iter_num': 7,
                                 'erode_iter_num': 2,
                                 'morph_kernel_size': 3,
                                 'name': 'point_render+gca'},
                'MAX_PER_GPU_PROCESS': 1,
                'Pose2dEstimator': {'cfg_path': './assets/configs/pose2d/openpose/body25.toml',
                                    'joint_type': 'OpenPose-Body-25',
                                    'name': 'openpose'},
                'Pose3dEstimator': {'batch_size': 32,
                                    'cfg_path': './assets/configs/pose3d/spin.toml',
                                    'name': 'spin',
                                    'num_workers': 4},
                'Pose3dRefiner': {'cfg_path': './assets/configs/pose3d/smplify.toml',
                                  'name': 'smplify',
                                  'use_lfbgs': True},
                'Tracker': {'tracker_name': 'max_box'},
                'estimate_boxes_first': True,
                'filter_invalid': True,
                'has_detector': True,
                'temporal': True,
                'use_smplify': True},
 'Train': {'D_adam_b1': 0.9,
           'D_adam_b2': 0.999,
           'G_adam_b1': 0.9,
           'G_adam_b2': 0.999,
           'aug_bg': False,
           'display_freq_s': 30,
           'face_factor': 1.0,
           'face_loss_path': './assets/checkpoints/losses/sphere20a_20171020.pth',
           'final_lr': 2e-06,
           'lambda_D_prob': 1.0,
           'lambda_face': 5.0,
           'lambda_mask': 5.0,
           'lambda_mask_smooth': 1.0,
           'lambda_rec': 10.0,
           'lambda_tsf': 10.0,
           'lr_D': 0.0001,
           'lr_G': 0.0001,
           'niters_or_epochs_decay': 0,
           'niters_or_epochs_no_decay': 100,
           'num_iters_validate': 1,
           'opti': 'Adam',
           'print_freq_s': 30,
           'save_latest_freq_s': 300,
           'tb_visual': False,
           'train_G_every_n_iterations': 1,
           'use_face': True,
           'use_vgg': 'VGG19',
           'vgg_loss_path': './assets/checkpoints/losses/vgg19-dcbb9e9d.pth'},
 'assets_dir': 'D:\\iPERCore-main/assets',
 'batch_size': 1,
 'bg_ks': 11,
 'cam_strategy': 'smooth',
 'cfg_path': './assets\\configs\\deploy.toml',
 'digital_type': 'cloth_smpl_link',
 'dis_name': 'patch_global',
 'face_path': './assets/checkpoints/pose3d/smpl_faces.npy',
 'facial_path': './assets/checkpoints/pose3d/front_facial.json',
 'fim_enc_path': './assets/checkpoints/pose3d/mapper_fim_enc.txt',
 'front_path': './assets/checkpoints/pose3d/front_body.json',
 'ft_ks': 1,
 'gen_name': 'AttLWB-SPADE',
 'gpu_ids': ['0'],
 'head_path': './assets/checkpoints/pose3d/head.json',
 'image_size': 256,
 'intervals': 1,
 'ip': '',
 'load_epoch': -1,
 'load_path_D': 'None',
 'load_path_G': './assets/checkpoints/neural_renders/AttLWB-SPADE_id_G_2020-05-18.pth',
 'local_rank': 0,
 'map_name': 'uv_seg',
 'meta_data': {'checkpoints_dir': 'D:\\iPERCore-main/results\\models\\model_1610192845.939266',
               'meta_ref': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001D52563A898>],
               'meta_src': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001D52563AEF0>],
               'opt_path': 'D:\\iPERCore-main/results\\models\\model_1610192845.939266\\opts.txt',
               'personalized_ckpt_path': 'D:\\iPERCore-main/results\\models\\model_1610192845.939266\\personalized.pth',
               'root_primitives_dir': 'D:\\iPERCore-main/results\\primitives'},
 'model_id': 'model_1610192845.939266',
 'neural_render_cfg': {'Discriminator': {'bg_cond_nc': 4,
                                         'cond_nc': 6,
                                         'max_nf_mult': 8,
                                         'n_layers': 4,
                                         'name': 'patch_global',
                                         'ndf': 64,
                                         'norm_type': 'instance',
                                         'use_sigmoid': False},
                       'Generator': {'BGNet': {'cond_nc': 4,
                                               'n_res_block': 6,
                                               'norm_type': 'instance',
                                               'num_filters': [64,
                                                               128,
                                                               128,
                                                               256]},
                                     'SIDNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'None',
                                                'num_filters': [64, 128, 256]},
                                     'TSFNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'instance',
                                                'num_filters': [64, 128, 256]},
                                     'name': 'AttLWB-SPADE'}},
 'neural_render_cfg_path': './assets/configs/neural_renders/AttLWB-SPADE.toml',
 'num_source': 2,
 'num_workers': 4,
 'only_vis': False,
 'output_dir': 'D:\\iPERCore-main/results',
 'part_path': './assets/checkpoints/pose3d/smpl_part_info.json',
 'port': 0,
 'ref_path': 'path?=D:\\iPERCore-main\\assets\\samples\\references\\akun_1.mp4,name?=akun_2,pose_fc?=300',
 'serial_batches': False,
 'share_bg': True,
 'smpl_model': './assets/checkpoints/pose3d/smpl_model.pkl',
 'smpl_model_hand': './assets/checkpoints/pose3d/smpl_model_with_hand_v2.pkl',
 'src_path': 'path?=D:\\iPERCore-main\\assets\\samples\\sources\\donald_trump_2\\00000.PNG,name?=donald_trump_2',
 'tb_visual': False,
 'temporal': False,
 'tex_size': 3,
 'time_step': 1,
 'train_name': 'LWGTrainer',
 'use_cudnn': False,
 'use_inpaintor': False,
 'uv_map_path': './assets/checkpoints/pose3d/mapper_uv.txt',
 'verbose': True}
-------------- End ----------------
        Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
        path: D:\iPERCore-main\assets\samples\sources\donald_trump_2\00000.PNG
        bg_path:
        name: donald_trump_2
primitives_dir: D:\iPERCore-main/results\primitives\donald_trump_2
processed_dir: D:\iPERCore-main/results\primitives\donald_trump_2\processed
vid_info_path: D:\iPERCore-main/results\primitives\donald_trump_2\processed\vid_info.pkl
-------------------------------------------------------
----------------------MetaProcess----------------------
meta_input:
        path: D:\iPERCore-main\assets\samples\references\akun_1.mp4
        bg_path:
        name: akun_2
        audio: D:\iPERCore-main/results\primitives\akun_2\processed\audio.mp3
        fps: 30.0
        pose_fc: 300.0
        cam_fc: 100
primitives_dir: D:\iPERCore-main/results\primitives\akun_2
processed_dir: D:\iPERCore-main/results\primitives\akun_2\processed
vid_info_path: D:\iPERCore-main/results\primitives\akun_2\processed\vid_info.pkl
-------------------------------------------------------
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 43, in run
    device=device
  File "D:\iPERCore-main\iPERCore\tools\processors\preprocessors.py", line 127, in __init__
    device=device
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 11, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "D:\anaconda3\envs\venv\lib\site-packages\mmdet\__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 138, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 212, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 142, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 235, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 155, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...

(venv) C:\WINDOWS\system32>
(venv) C:\WINDOWS\system32>python D:\iPERCore-main\demo\motion_imitate.py  --gpu_ids 0  --image_size 256  --num_source 2    --output_dir "D:\iPERCore-main/results"  --assets_dir "D:\iPERCore-main/assets"   --src_path   "path?=D:\iPERCore-main\assets\samples\sources\donald_trump_2\00000.PNG,name?=donald_trump_2"  --ref_path   "path?=D:\iPERCore-main\assets\samples\references\akun_1.mp4,name?=akun_2,pose_fc?=300"
./assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe -v error -select_streams v -of default=noprint_wrappers=1:nokey=1 -show_entries stream=r_frame_rate D:\iPERCore-main\assets\samples\references\akun_1.mp4
------------ Options -------------
{'MAX_NUM_SOURCE': 8,
 'MultiMedia': {'ffmpeg': {'Linux': {'ffmpeg_exe_path': 'ffmpeg',
                                     'ffprobe_exe_path': 'ffprobe'},
                           'Windows': {'ffmpeg_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe',
                                       'ffprobe_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe'},
                           'pix_fmt': 'yuv420p',
                           'vcodec': 'h264'},
                'image': {'caption': 'this is a fake video, synthesized by '
                                     'impersonator++',
                          'saved_name_format': 'pred_{:0>8}.png'}},
 'NUMBER_FACES': 13776,
 'NUMBER_VERTS': 6890,
 'Preprocess': {'BackgroundInpaintor': {'bg_replace': True,
                                        'cfg_path': './assets/configs/inpaintors/mmedit_inpainting.toml',
                                        'dilate_iter_num': 3,
                                        'dilate_kernel_size': 9,
                                        'name': 'mmedit_inpainting',
                                        'use_sr': True},
                'Cropper': {'ref_crop_factor': 3.0, 'src_crop_factor': 1.3},
                'Deformer': {'cloth_parse_ckpt_path': './assets/checkpoints/mattors/exp-schp-lip.pth'},
                'FrontInfo': {'NUM_CANDIDATE': 25, 'RENDER_SIZE': 256},
                'HumanMattors': {'cfg_path': './assets/configs/mattors/point_render+gca.toml',
                                 'dilate_iter_num': 7,
                                 'erode_iter_num': 2,
                                 'morph_kernel_size': 3,
                                 'name': 'point_render+gca'},
                'MAX_PER_GPU_PROCESS': 1,
                'Pose2dEstimator': {'cfg_path': './assets/configs/pose2d/openpose/body25.toml',
                                    'joint_type': 'OpenPose-Body-25',
                                    'name': 'openpose'},
                'Pose3dEstimator': {'batch_size': 32,
                                    'cfg_path': './assets/configs/pose3d/spin.toml',
                                    'name': 'spin',
                                    'num_workers': 4},
                'Pose3dRefiner': {'cfg_path': './assets/configs/pose3d/smplify.toml',
                                  'name': 'smplify',
                                  'use_lfbgs': True},
                'Tracker': {'tracker_name': 'max_box'},
                'estimate_boxes_first': True,
                'filter_invalid': True,
                'has_detector': True,
                'temporal': True,
                'use_smplify': True},
 'Train': {'D_adam_b1': 0.9,
           'D_adam_b2': 0.999,
           'G_adam_b1': 0.9,
           'G_adam_b2': 0.999,
           'aug_bg': False,
           'display_freq_s': 30,
           'face_factor': 1.0,
           'face_loss_path': './assets/checkpoints/losses/sphere20a_20171020.pth',
           'final_lr': 2e-06,
           'lambda_D_prob': 1.0,
           'lambda_face': 5.0,
           'lambda_mask': 5.0,
           'lambda_mask_smooth': 1.0,
           'lambda_rec': 10.0,
           'lambda_tsf': 10.0,
           'lr_D': 0.0001,
           'lr_G': 0.0001,
           'niters_or_epochs_decay': 0,
           'niters_or_epochs_no_decay': 100,
           'num_iters_validate': 1,
           'opti': 'Adam',
           'print_freq_s': 30,
           'save_latest_freq_s': 300,
           'tb_visual': False,
           'train_G_every_n_iterations': 1,
           'use_face': True,
           'use_vgg': 'VGG19',
           'vgg_loss_path': './assets/checkpoints/losses/vgg19-dcbb9e9d.pth'},
 'assets_dir': 'D:\\iPERCore-main/assets',
 'batch_size': 1,
 'bg_ks': 11,
 'cam_strategy': 'smooth',
 'cfg_path': './assets\\configs\\deploy.toml',
 'digital_type': 'cloth_smpl_link',
 'dis_name': 'patch_global',
 'face_path': './assets/checkpoints/pose3d/smpl_faces.npy',
 'facial_path': './assets/checkpoints/pose3d/front_facial.json',
 'fim_enc_path': './assets/checkpoints/pose3d/mapper_fim_enc.txt',
 'front_path': './assets/checkpoints/pose3d/front_body.json',
 'ft_ks': 1,
 'gen_name': 'AttLWB-SPADE',
 'gpu_ids': ['0'],
 'head_path': './assets/checkpoints/pose3d/head.json',
 'image_size': 256,
 'intervals': 1,
 'ip': '',
 'load_epoch': -1,
 'load_path_D': 'None',
 'load_path_G': './assets/checkpoints/neural_renders/AttLWB-SPADE_id_G_2020-05-18.pth',
 'local_rank': 0,
 'map_name': 'uv_seg',
 'meta_data': {'checkpoints_dir': 'D:\\iPERCore-main/results\\models\\model_1610193396.8610756',
               'meta_ref': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001A5253349B0>],
               'meta_src': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001A525334CF8>],
               'opt_path': 'D:\\iPERCore-main/results\\models\\model_1610193396.8610756\\opts.txt',
               'personalized_ckpt_path': 'D:\\iPERCore-main/results\\models\\model_1610193396.8610756\\personalized.pth',
               'root_primitives_dir': 'D:\\iPERCore-main/results\\primitives'},
 'model_id': 'model_1610193396.8610756',
 'neural_render_cfg': {'Discriminator': {'bg_cond_nc': 4,
                                         'cond_nc': 6,
                                         'max_nf_mult': 8,
                                         'n_layers': 4,
                                         'name': 'patch_global',
                                         'ndf': 64,
                                         'norm_type': 'instance',
                                         'use_sigmoid': False},
                       'Generator': {'BGNet': {'cond_nc': 4,
                                               'n_res_block': 6,
                                               'norm_type': 'instance',
                                               'num_filters': [64,
                                                               128,
                                                               128,
                                                               256]},
                                     'SIDNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'None',
                                                'num_filters': [64, 128, 256]},
                                     'TSFNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'instance',
                                                'num_filters': [64, 128, 256]},
                                     'name': 'AttLWB-SPADE'}},
 'neural_render_cfg_path': './assets/configs/neural_renders/AttLWB-SPADE.toml',
 'num_source': 2,
 'num_workers': 4,
 'only_vis': False,
 'output_dir': 'D:\\iPERCore-main/results',
 'part_path': './assets/checkpoints/pose3d/smpl_part_info.json',
 'port': 0,
 'ref_path': 'path?=D:\\iPERCore-main\\assets\\samples\\references\\akun_1.mp4,name?=akun_2,pose_fc?=300',
 'serial_batches': False,
 'share_bg': True,
 'smpl_model': './assets/checkpoints/pose3d/smpl_model.pkl',
 'smpl_model_hand': './assets/checkpoints/pose3d/smpl_model_with_hand_v2.pkl',
 'src_path': 'path?=D:\\iPERCore-main\\assets\\samples\\sources\\donald_trump_2\\00000.PNG,name?=donald_trump_2',
 'tb_visual': False,
 'temporal': False,
 'tex_size': 3,
 'time_step': 1,
 'train_name': 'LWGTrainer',
 'use_cudnn': False,
 'use_inpaintor': False,
 'uv_map_path': './assets/checkpoints/pose3d/mapper_uv.txt',
 'verbose': True}
-------------- End ----------------
        Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
        path: D:\iPERCore-main\assets\samples\sources\donald_trump_2\00000.PNG
        bg_path:
        name: donald_trump_2
primitives_dir: D:\iPERCore-main/results\primitives\donald_trump_2
processed_dir: D:\iPERCore-main/results\primitives\donald_trump_2\processed
vid_info_path: D:\iPERCore-main/results\primitives\donald_trump_2\processed\vid_info.pkl
-------------------------------------------------------
----------------------MetaProcess----------------------
meta_input:
        path: D:\iPERCore-main\assets\samples\references\akun_1.mp4
        bg_path:
        name: akun_2
        audio: D:\iPERCore-main/results\primitives\akun_2\processed\audio.mp3
        fps: 30.0
        pose_fc: 300.0
        cam_fc: 100
primitives_dir: D:\iPERCore-main/results\primitives\akun_2
processed_dir: D:\iPERCore-main/results\primitives\akun_2\processed
vid_info_path: D:\iPERCore-main/results\primitives\akun_2\processed\vid_info.pkl
-------------------------------------------------------
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 43, in run
    device=device
  File "D:\iPERCore-main\iPERCore\tools\processors\preprocessors.py", line 127, in __init__
    device=device
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 11, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "D:\anaconda3\envs\venv\lib\site-packages\mmdet\__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 138, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 212, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 142, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 235, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 155, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...

**Comment by bumie7758258** [comment]
这是我的配置
Package          Version     Location
---------------- ----------- -------------------
addict           2.4.0
certifi          2020.12.5
chardet          4.0.0
cross            1.0.3
cycler           0.10.0
Cython           0.29.21
decorator        4.4.2
easydict         1.9
future           0.18.2
idna             2.10
imageio          2.9.0
iPERCore         0.1.1       c:\windows\system32
jsonpatch        1.28
jsonpointer      2.0
kiwisolver       1.3.1
matplotlib       3.3.3
mmcv-full        1.1.5
mmdet            2.8.0
mmedit           0.5.0
mmpycocotools    12.0.3
networkx         2.5
neural-renderer  1.1.3
numpy            1.19.3
opencv-python    4.5.1.48
Pillow           8.1.0
pip              20.3.3
protobuf         3.14.0
pyparsing        2.4.7
python-dateutil  2.8.1
PyWavelets       1.1.1
PyYAML           5.3.1
pyzmq            20.0.0
regex            2020.11.13
requests         2.25.1
scikit-image     0.17.2
scipy            1.5.4
setuptools       36.4.0
six              1.15.0
tensorboardX     2.1
terminaltables   3.1.0
tifffile         2020.9.3
toml             0.10.2
torch            1.6.0+cu101
torchfile        0.1.0
torchvision      0.7.0+cu101
tornado          6.1
tqdm             4.55.1
urllib3          1.26.2
visdom           0.1.8.9
websocket-client 0.57.0
wheel            0.29.0
wincertstore     0.2
yapf             0.30.0

**Comment by anguoKuang** [comment]
> 这是我的配置
> Package Version Location
> 
> addict 2.4.0
> certifi 2020.12.5
> chardet 4.0.0
> cross 1.0.3
> cycler 0.10.0
> Cython 0.29.21
> decorator 4.4.2
> easydict 1.9
> future 0.18.2
> idna 2.10
> imageio 2.9.0
> iPERCore 0.1.1 c:\windows\system32
> jsonpatch 1.28
> jsonpointer 2.0
> kiwisolver 1.3.1
> matplotlib 3.3.3
> mmcv-full 1.1.5
> mmdet 2.8.0
> mmedit 0.5.0
> mmpycocotools 12.0.3
> networkx 2.5
> neural-renderer 1.1.3
> numpy 1.19.3
> opencv-python 4.5.1.48
> Pillow 8.1.0
> pip 20.3.3
> protobuf 3.14.0
> pyparsing 2.4.7
> python-dateutil 2.8.1
> PyWavelets 1.1.1
> PyYAML 5.3.1
> pyzmq 20.0.0
> regex 2020.11.13
> requests 2.25.1
> scikit-image 0.17.2
> scipy 1.5.4
> setuptools 36.4.0
> six 1.15.0
> tensorboardX 2.1
> terminaltables 3.1.0
> tifffile 2020.9.3
> toml 0.10.2
> torch 1.6.0+cu101
> torchfile 0.1.0
> torchvision 0.7.0+cu101
> tornado 6.1
> tqdm 4.55.1
> urllib3 1.26.2
> visdom 0.1.8.9
> websocket-client 0.57.0
> wheel 0.29.0
> wincertstore 0.2
> yapf 0.30.0

卸载了重新安装试试，不知道你是不是安装成了cpu版本？或者直接去下载对应的whl文件安装

**Comment by bumie7758258** [comment]
我又重试了一下，我是直接下的whl文件安装的，文件名是mmcv-full-1.1.5+torch1.6.0＋cu101-cp36-cp36m-win–amd64.whl 还是不行------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;anguoKuang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月12日(星期二) 晚上10:03
收件人:&nbsp;&quot;iPERDance/iPERCore&quot;<iPERCore@noreply.github.com&gt;;
抄送:&nbsp;&quot;bumie7758258&quot;<554635006@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iPERDance/iPERCore] 大佬们运行motion_imitate.py时老是报错mmcv-full 1.1.5版本不匹配怎么解决啊 (#62)

**Comment by piaozhx** [comment]
@bumie7758258  安装指定版本的mmdet, 不要安装最新版本的

**Comment by bumie7758258** [comment]
成功了！困扰了我好几天，万分感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Zhixin&amp;nbsp;Piao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月12日(星期二) 晚上11:20
收件人:&nbsp;&quot;iPERDance/iPERCore&quot;<iPERCore@noreply.github.com&gt;;
抄送:&nbsp;&quot;bumie7758258&quot;<554635006@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iPERDance/iPERCore] 大佬们运行motion_imitate.py时老是报错mmcv-full 1.1.5版本不匹配怎么解决啊 (#62)
