### ISSUE TITLE
AssertionError: MMCV==1.2.4 is used but incompatible. Please install mmcv>=[1, 0, 2], <=[1, 2].

### ISSUE THREAD

**Issue by Wolf-KING-A** [iPERDance/iPERCore#67]
运行python demo/motion_imitate.py --gpu_ids 0 \
   --image_size 512 \
   --num_source 2   \
   --output_dir "./results" \
   --assets_dir "./assets"  \
   --model_id   "donald_trump_2" \
   --src_path   "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" \
   --ref_path   "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"命令报错.
基础环境为docker容器中ubuntu16.04+cuda10.1+torch1.7.0-cu101，各种依赖报均安装成功，但报以上问题的错误

**Comment by piaozhx** [comment]
@Wolf-KING-A 安装时有手动指定`mmcv`或`mmdet`的版本吗?

**Comment by IItaly** [comment]
mmcv对应1.7.0的只有1.2.0及以上的版本，而mmedit要求“MMCV==1.2.0 is used but incompatible. Please install mmcv>=[1, 0, 2], <=[1, 2]. ” 装了mmcv==1.2.0，mmdet==2.7.0 mmedit==0.5.0依然报错

**Comment by piaozhx** [comment]
@IItaly 安装指定reqs中指定版本的mm系列相关的包, 不要手动安装某个版本

**Comment by Wolf-KING-A** [comment]
我通过修改mmcv报错的文件里的代码，解决了这个问题，在__init__.py文件中（具体路径忘记了，可以看下报错日志）的MMCV_MAX==[1.2]改为[1.2.5]就不报这个问题了

**Comment by IItaly** [comment]
T T 但是cuda是11的 3080是不是不能试了

**Comment by piaozhx** [comment]
@Wolf-KING-A 你说得对, mm系列的版本其实没有他标定的那么严格, 但是依照我们reqs中给定的版本安装是不会出现问题的.

**Comment by IItaly** [comment]
> 我通过修改mmcv报错的文件里的代码，解决了这个问题，在__init__.py文件中（具体路径忘记了，可以看下报错日志）的MMCV_MAX==[1.2]改为[1.2.5]就不报这个问题了

我也修改成了1.2.0 T T

**Comment by piaozhx** [comment]
@IItaly 显卡型号与cuda版本无关, 你是3080也可以安装cuda10.1的. 
不过目前cuda11的兼容性不是很好, 很多库没有相应的预编译包

**Comment by IItaly** [comment]
> @IItaly 显卡型号与cuda版本无关, 你是3080也可以安装cuda10.1的.
> 不过目前cuda11的兼容性不是很好, 很多库没有相应的预编译包

好的 那我照给定装

**Comment by Wolf-KING-A** [comment]
是的 按照reqs中给定的版本安装 出现错误可以根据报错日志的提示来寻求解决办法。我在基础环境为docker容器中ubuntu16.04+cuda10.1+torch1.7.0-cu101的这个环境下已成功跑通demo @piaozhx @IItaly
