### ISSUE TITLE
How can I download all pred_*.png files from colab?

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#68]
I can only run iPERDance with image_size=384 locally because otherwise it will fail with cuda out of memory.
I can use my PC to experiment. But for final result I want to get the best quality. So I use colab. Is there a way to download all PNG files from the colab result folder? If it's not possible it would be great to have a cell to zip all PNG files.

thanks

**Comment by mr-aliftin** [comment]
You can pack it into an archive and download it in one file.

`!cd /content/
!tar -cvf file.tar content/iPERCore/full/path/to/images`

**Comment by bigboss97** [comment]
It works, thanks.
