### ISSUE TITLE
RuntimeError: Tensor for argument #3 'mat2' is on CPU

### ISSUE THREAD

**Issue by lauramercier** [iPERDance/iPERCore#70]
RuntimeError: Tensor for argument #3 'mat2' is on CPU, but expected it to be on GPU (while checking arguments for addmm)
v_shaped = torch.matmul(beta, self.shapedirs).view(-1, self.size[0], self.size[1]) + self.v_template + offsets
"torch.matmul" seems to be defined in tools->human_digitalizer->bodynets->batch_smpl->SMPL->__init__

**Comment by StevenLiuWen** [comment]
hi, currently, it must need an nvidia-gpu device yet. If you do not have it, try to use the colab, https://colab.research.google.com/drive/1bwUnj-9NnJA2EMr7eWO4I45UuBtKudg_?usp=sharing
