### ISSUE TITLE
生成的视频模糊不清

### ISSUE THREAD

**Issue by zxq2233** [iPERDance/iPERCore#71]
https://www.bilibili.com/video/BV1zo4y1o7sG
如何解决

如图，我只需要最终输出的视频，不需要原图像，应该修改代码哪里
#
![360截图20210115091557538](https://user-images.githubusercontent.com/14195738/104668146-835efb80-5712-11eb-93a3-c07e27753d44.jpg)

**Comment by StevenLiuWen** [comment]
@zxq2233，可以增加image_size, 例如--image_size 512
