### ISSUE TITLE
Scripts for appearance transfer

### ISSUE THREAD

**Issue by htzheng** [iPERDance/iPERCore#73]
In the ICCV version, there is a script "python run_swap.py" for appearance transfer. I wonder if there are similar scripts for appearance transfer like the ICCV paper? Thank you.

**Comment by ralphthehacker** [comment]
+1. Really interested in replicating results in appearance transfer

**Comment by StevenLiuWen** [comment]
Hi, @htzheng and @ralphthehacker, we have updated the iPERCore with the 0.2.0 version, which contains the appearance transfer codes; enjoy it.

**Comment by htzheng** [comment]
@StevenLiuWen Thank you a lot for updating iPERCore to 0.2.0! However, after the update, the code seems to crash after running the basic script. For example, when running the script for "imitates one references"
`python demo/motion_imitate.py --gpu_ids 0 \
   --image_size 512 \
   --num_source 2   \
   --output_dir "./results" \
   --assets_dir "./assets"  \
   --model_id   "donald_trump_2" \
   --src_path   "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" \
   --ref_path   "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"`
  There appear an error
  `    smpls = estimated_smpls[valid_img_info["parse_ids"]]
KeyError: 'parse_ids'`

Also the demo/motion_imitate.py cannot find the iPERCore package from the parent directory:
`  File "demo/motion_imitate.py", line 12, in <module>
    from iPERCore.services.options.options_setup import setup
ModuleNotFoundError: No module named 'iPERCore'`

Because this issue affects the entire code, I would really hope for a quick fix there. Thanks again!

**Comment by StevenLiuWen** [comment]
@htzheng , It seems that you have not installed it or installed it failed, and try to follow the installation instructions for more details. https://github.com/iPERDance/iPERCore/blob/main/docs/install.md
