### ISSUE TITLE
No such file or directory when installing neural_renderer

### ISSUE THREAD

**Issue by xielongze** [iPERDance/iPERCore#77]
I'm trying to install it on ubuntu16.04, pytorch1.7.0, cuda11.0.194 and I have the following error compiling neural_renderer. Do you have any idea how to solve this issue? Thanks~
python -m pip install git+https://github.com/iPERDance/neural_renderer.git@e5f54f71a8941acf372514eb92e289872f272653

Collecting git+https://github.com/iPERDance/neural_renderer.git@e5f54f71a8941acf372514eb92e289872f272653

  Cloning https://github.com/iPERDance/neural_renderer.git (to revision e5f54f71a8941acf372514eb92e289872f272653) to /tmp/pip-req-build-ilitesl6
Requirement already satisfied: numpy in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (1.19.3)
Requirement already satisfied: torch in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (1.7.0)
Requirement already satisfied: torchvision in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (0.8.1+cu101)
Requirement already satisfied: scikit-image in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (0.17.2)
Requirement already satisfied: tqdm in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (4.48.2)
Requirement already satisfied: imageio in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from neural-renderer==1.1.3) (2.9.0)
Requirement already satisfied: future in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from torch->neural-renderer==1.1.3) (0.18.2)
Requirement already satisfied: typing_extensions in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from torch->neural-renderer==1.1.3) (3.7.4.3)
Requirement already satisfied: dataclasses in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from torch->neural-renderer==1.1.3) (0.8)
Requirement already satisfied: pillow>=4.1.1 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from torchvision->neural-renderer==1.1.3) (8.1.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from scikit-image->neural-renderer==1.1.3) (3.3.3)
Requirement already satisfied: tifffile>=2019.7.26 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from scikit-image->neural-renderer==1.1.3) (2020.9.3)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from scikit-image->neural-renderer==1.1.3) (1.1.1)
Requirement already satisfied: scipy>=1.0.1 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from scikit-image->neural-renderer==1.1.3) (1.5.2)
Requirement already satisfied: networkx>=2.0 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from scikit-image->neural-renderer==1.1.3) (2.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural-renderer==1.1.3) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural-renderer==1.1.3) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural-renderer==1.1.3) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural-renderer==1.1.3) (0.10.0)
Requirement already satisfied: decorator>=4.3.0 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from networkx>=2.0->scikit-image->neural-renderer==1.1.3) (4.4.2)
Requirement already satisfied: six>=1.5 in /home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image->neural-renderer==1.1.3) (1.15.0)
Building wheels for collected packages: neural-renderer
  Building wheel for neural-renderer (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubun/anaconda3/envs/ipercore/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ilitesl6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ilitesl6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qzz7cgpw
       cwd: /tmp/pip-req-build-ilitesl6/
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/save_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/projection.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/renderer.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/mesh.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/rasterize.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/perspective.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/rasterize_test.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/vertices_to_faces.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/look.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/lighting.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/get_points_from_angles.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/load_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
  copying neural_renderer/look_at.py -> build/lib.linux-x86_64-3.6/neural_renderer
  creating build/lib.linux-x86_64-3.6/neural_renderer/cuda
  copying neural_renderer/cuda/rasterize.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
  copying neural_renderer/cuda/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
  copying neural_renderer/cuda/create_texture_image.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
  copying neural_renderer/cuda/load_textures.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
  running build_ext
  building 'neural_renderer.cuda.load_textures' extension
  creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6
  creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer
  creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda
  Emitting ninja build file /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  1.10.2
  g++ -pthread -shared -B /home/ubun/anaconda3/envs/ipercore/compiler_compat -L/home/ubun/anaconda3/envs/ipercore/lib -Wl,-rpath=/home/ubun/anaconda3/envs/ipercore/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda.o /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda_kernel.o -L/home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda-11.0/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so
  **g++: error: /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda.o: No such file or directory
  g++: error: /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda_kernel.o: No such file or directory**
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for neural-renderer
  Running setup.py clean for neural-renderer
Failed to build neural-renderer
Installing collected packages: neural-renderer
    Running setup.py install for neural-renderer ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubun/anaconda3/envs/ipercore/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ilitesl6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ilitesl6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-564t_vm0/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubun/anaconda3/envs/ipercore/include/python3.6m/neural-renderer
         cwd: /tmp/pip-req-build-ilitesl6/
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/save_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/projection.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/renderer.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/mesh.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/rasterize.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/perspective.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/rasterize_test.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/vertices_to_faces.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/look.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/lighting.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/get_points_from_angles.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/load_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/look_at.py -> build/lib.linux-x86_64-3.6/neural_renderer
    creating build/lib.linux-x86_64-3.6/neural_renderer/cuda
    copying neural_renderer/cuda/rasterize.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
    copying neural_renderer/cuda/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
    copying neural_renderer/cuda/create_texture_image.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
    copying neural_renderer/cuda/load_textures.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
    running build_ext
    building 'neural_renderer.cuda.load_textures' extension
    creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6
    creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer
    creating /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda
    Emitting ninja build file /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2
    g++ -pthread -shared -B /home/ubun/anaconda3/envs/ipercore/compiler_compat -L/home/ubun/anaconda3/envs/ipercore/lib -Wl,-rpath=/home/ubun/anaconda3/envs/ipercore/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda.o /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda_kernel.o -L/home/ubun/anaconda3/envs/ipercore/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda-11.0/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so
    ### **g++: error: /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda.o: No such file or directory
    g++: error: /tmp/pip-req-build-ilitesl6/build/temp.linux-x86_64-3.6/neural_renderer/cuda/load_textures_cuda_kernel.o: No such file or directory**
    error: command 'g++' failed with exit status 1

**Comment by LeoLee321** [comment]
How did you solve it?
