### ISSUE TITLE
i meet some errors when following the guideline

### ISSUE THREAD

**Issue by zzr9zzr** [iPERDance/iPERCore#80]
FileNotFoundError: [Errno 2] No such file or directory: './assets/checkpoints/pose2d/openpose_body25.pth'
                Pre-processing: digital deformation start...

FileNotFoundError: [Errno 2] No such file or directory: './assets/checkpoints/pose3d/smpl_model.pkl'
                Pre-processing: digital deformation completed...

it is an excellent project and i want to run in my computer but there are some errors

**Comment by StevenLiuWen** [comment]
hi @zzr9zzr, you need to download the resources file firstly and unzip then into the assets folder. See https://github.com/iPERDance/iPERCore/blob/main/docs/install.md#download-checkpoints-and-samples for more details.

**Comment by zzr9zzr** [comment]
thx very much！

**Comment by basemdabbour** [comment]
Hi, 
The checkpoint server is down and i am not able to download it
please can you share it or do you know any other way of doing it?

Thanks
