### ISSUE TITLE
Cannot download checkpoints/samples 

### ISSUE THREAD

**Issue by justinjohn0306** [iPERDance/iPERCore#81]

**Comment by Cursky** [comment]
me too 。

**Comment by basemdabbour** [comment]
I have the same issue, seems like the server is down
anyone can provide the checkpoint folder 1.3 GB?

**Comment by justinjohn0306** [comment]
https://mega.nz/file/UshQVYoB#Ajt8oAlD-M667vBVch5C-IzRszlZ2XjAeLR6dQf1nHs

**Comment by barhilleli** [comment]
Can you please also provide the samples folder?

**Comment by justinjohn0306** [comment]
> Can you please also provide the samples folder?

Sure, here you go : https://mega.nz/file/09RnwaRL#-IwCS0kNbBKhCOy6YhC3fWVRimVHvaDs8f3A3Zk9NVc

**Comment by inuboshi** [comment]
Any chances of a re-upload of the windows release? (iper_windows_released.7z)
Link is dead.

**Comment by piaozhx** [comment]
@justinjohn0306  @barhilleli @inuboshi @Cursky  @basemdabbour  Sorry for the late response, the original one drive server has been closed. we have fixed this problem and now all links work well.

**Comment by justinjohn0306** [comment]
> @justinjohn0306 @barhilleli @inuboshi @Cursky @basemdabbour Sorry for the late response, the original one drive server has been closed. we have fixed this problem and now all links work well.

Thank you very much!!
Let's close this issue now
