### ISSUE TITLE
iPERDance checkpoint server is down!! - ANY Solution 

### ISSUE THREAD

**Issue by basemdabbour** [iPERDance/iPERCore#82]
Hello, we can't connect to the asset's server to download checkpoints and samples, it is giving timeout!.

!wget -O assets/checkpoints.zip "https://download.impersonator.org/iper_plus_plus_latest_checkpoints.zip"
and this
!wget -O assets/samples.zip  "https://download.impersonator.org/iper_plus_plus_latest_samples.zip"

It seems like the server is down, do u have any way to download the checkpoints?

**Comment by justinjohn0306** [comment]
https://mega.nz/file/UshQVYoB#Ajt8oAlD-M667vBVch5C-IzRszlZ2XjAeLR6dQf1nHs

**Comment by basemdabbour** [comment]
@justinjohn0306 
hey, thanks. Do you know a way where i can upload the zip folder and use the link in the wget command?

**Comment by justinjohn0306** [comment]
😂 I did everything manually

**Comment by basemdabbour** [comment]
@justinjohn0306 
hahah, i did that as well and uploaded the checkpoint folder to my Google Drive, but it is not fetching the subfolders in colab!!!

**Comment by basemdabbour** [comment]
@justinjohn0306 hahaha i did that as well, it worked.
