### ISSUE TITLE
Pre-Compiled Link Dead

### ISSUE THREAD

**Issue by LuigiHard** [iPERDance/iPERCore#87]
Title says it all 
![image](https://user-images.githubusercontent.com/79230985/112243608-a33bff80-8c2c-11eb-84e9-b7a8106ce7e6.png)
This page is not working (but written in Portuguese cause I'm Brazilian)

**Comment by rinukkusu** [comment]
Yeah, can't download the checkpoints.zip either ...

**Comment by LosBagros** [comment]
Same

**Comment by Slithersy** [comment]
> Yeah, can't download the checkpoints.zip either ...

https://github.com/iPERDance/iPERCore/blob/main/docs/install.md
At the bottom you have links that do work to download checkpoints.zip



> Title says it all

For the pre-compiled version on windows, use the first download button over here, it works for me. 
https://github.com/iPERDance/iPERCore/wiki/How-to-use-the-released-version-on-windows%3F

**Comment by rinukkusu** [comment]
Then I guess the links in the install.md file need to be fixed.

**Comment by FlashlightET** [comment]
`For the pre-compiled version on windows, try this: (It's a redirect from the download link you tried, the first link works sometimes therefore I managed to get it)
https://download.impersonator.org/iper_windows_released.7z` 
same error

**Comment by Slithersy** [comment]
> `For the pre-compiled version on windows, try this: (It's a redirect from the download link you tried, the first link works sometimes therefore I managed to get it) https://download.impersonator.org/iper_windows_released.7z`
> same error

Odd.. it seems to work at certain times and not work at other times.
I'll try to upload it when I get the chance.

**Comment by Slithersy** [comment]
Samples & Checkpoints: (adjusted a bit but should be around the same):
https://drive.google.com/file/d/15wLrdbiBZ7Q4O_8Dxmkd3ztvMtpCBMew/view?usp=sharing

Pre-Complied link:
https://drive.google.com/file/d/1XP-QfNQVw6mjCM7wlDtiP7DRIN2Mxpcd/view?usp=sharing
