### ISSUE TITLE
Faild to run when using a folder of image for a person

### ISSUE THREAD

**Issue by acc557** [iPERDance/iPERCore#9]
```
1.1 Preprocessing, running Preprocessor to detect the human boxes of ./results/primitives/processed/orig_images...
  0% 0/5 [00:00<?, ?it/s]
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 77, in run
    visual=True,
  File "/content/iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 81, in execute
    self._execute_detector(processed_info, factor=factor)
  File "/content/iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 298, in _execute_detector
    cur_shape = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 80, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
		Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "/content/iPERCore/iPERCore/services/options/process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "/content/iPERCore/iPERCore/services/options/process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: failed...
```

**Comment by acc557** [comment]
It seems that it fails to detect the person in the folder. However, using one image will work without any problem.

**Comment by StevenLiuWen** [comment]
@acc557 Firstly, there must be a person in the source image. Also, what's the **src_path** in your script, and the `path` must be correct in the **src_path**.

**Comment by acc557** [comment]
@StevenLiuWen 
 There was one and only person in the source image. 
I am running on colab and you can reproduce this issue by changing the src_path from
```
src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6=ns=2," \
             "name?=afan_6=ns=2," \
             "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""
```
to
```
src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6" \
             "name?=afan_6=ns=2," \
             "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""
```

The new folder contains more than one image from afan_6, and it crashes the code.

**Comment by acc557** [comment]
I think the bug may be related to detecting the the front and back of the person.

I tried the front and back image respectively and they both works fine when they are not in a folder.

Is it possible to bypass the detection and use a prefix or suffix in filename to specify the front or back?

**Comment by StevenLiuWen** [comment]
@acc557 , It seems that you rename the same `name?=afan_6=ns=2`. The `name` must be **unique**.

**Comment by acc557** [comment]
> 
> 
> @acc557 , It seems that you rename the same `name?=afan_6=ns=2`. The `name` must be **unique**. It seems that there is a name with `afan_6=ns=2` with only two images. While you want to use the folder `afan_6` with more than two images. They are different inputs. You might need to change it to
> 
> ```shell
> src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6," \
>              "name?=afan_6," \
>              "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""
> ```

I also tried this, but saw the same error. I also tired using my own images(only two), but the problem persists.

**Comment by StevenLiuWen** [comment]
@acc557, we can run it successfully with the `afan_6` folder. If your `outputs_dir` is './results'.
You delete the folder `./results/models/afan` and `results/primitives/afan_6`, and run the script again.

**Comment by acc557** [comment]
> 
> 
> @acc557, we can run it successfully with the `afan_6` folder. If your `outputs_dir` is './results'.
> You delete the folder `./results/models/afan` and `results/primitives/afan_6`, and run the script again.

It seems to work the `afan_6` folder after deleting the result folder. Now I am trying my own images.

**Comment by StevenLiuWen** [comment]
@acc557 Ok. It seems that when the preprocessing failed, (mostly happens with rename withe same project name, or the path does not exist), our system did not clean the `processed` folder, and will still encounter some problems when the name is unique and put the right path.

**Comment by acc557** [comment]
Thanks! It works great this time. :) 

I guess that colab was doing something strange last time.
