### ISSUE TITLE
如何提高inference速度呢？

### ISSUE THREAD

**Issue by ymzlygw** [iPERDance/iPERCore#95]
在Colab上跑第一个例子发现从开始到生成一个结果要10多分钟左右，这个速度正常么？如何加快推理速度呢

**Comment by ymzlygw** [comment]
> 在Colab上跑第一个例子发现从开始到生成一个结果要10分钟左右，这个速度正常么？如何加快推理速度呢

**Comment by StevenLiuWen** [comment]
@ymzlygw ,colab上分配的卡比较随机，有时候分配的 比较差的话，时间会久一点。
