### ISSUE TITLE
Can I use a video as a source?

### ISSUE THREAD

**Issue by LeoLee321** [iPERDance/iPERCore#99]
Can I use a video as a source? And it will automatically capture the best frame of the video as a source image.
Do you know how to achieve it？

**Comment by Aryan-Solanki** [comment]
> Can I use a video as a source? And it will automatically capture the best frame of the video as a source image.
> Do you know how to achieve it？

You can use OpenCV  to  extract imgs from videos https://www.geeksforgeeks.org/extract-images-from-video-in-python/
then just apply some img /body recognition which will find best img for you

**Comment by LeoLee321** [comment]
> > Can I use a video as a source? And it will automatically capture the best frame of the video as a source image.
> > Do you know how to achieve it？
> 
> You can use OpenCV to extract imgs from videos https://www.geeksforgeeks.org/extract-images-from-video-in-python/
> then just apply some img /body recognition which will find best img for you

Yeah, I made it. Thank you
